{{- if .Values.secrets.external.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-secrets
spec:
  refreshInterval: 60s
  secretStoreRef:
    name: {{ .Values.secrets.external.storeName }}
    kind: ClusterSecretStore
  target:
    name: {{ .Release.Name }}-secrets
    creationPolicy: Owner
  data:
    - { secretKey: PYTH_HERMES_URL, remoteRef: { key: {{ .Values.secrets.external.paths.pythHermesUrl }} } }
{{- end }}
