[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.17"

[features]
resolution = true
skip-lint = false

[programs.localnet]
earn_vault = "EarnVau1tProgr4mPubKeyP1ace0001111111111111"
internal_swap = "InternalSwapProgr4mPubKeyP1ace0001111111111"
pomm = "PommProgr4mPubKeyP1ace00011111111111111111"
ping_token = "PingTokenProgr4mPubKeyP1ace00011111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = [
  "programs/earn-vault",
  "programs/internal-swap",
  "programs/pomm",
  "programs/ping-token",
]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
