use anchor_lang::prelude::*;
use anchor_spl::token_interface::{
    self, Mint, TokenAccount, TokenInterface, TransferChecked,
};

// ============================================================================
// ⚠️  DO NOT DEPLOY THIS PROGRAM TO MAINNET — per ADR 0018 + #22 EPIC gates.
// ============================================================================
// Pre-audit class-pattern fixes will be filed once a dedicated review runs;
// known scaffold smells inherited from earn-vault review #2 (#22 c.4527111355):
//   - seeds = [b"treasury"] front-runnable single global PDA (6 call sites) →
//     fix per C-04 pattern (bind to usdc_mint, see earn-vault f7ea54f)
//   - no rotate_authority instruction → migrate-to-multisig path missing
//     per ping-token H-03 (f1cfab4) + earn-vault H-04 (2d89968)
//   - deploy_to_clmm has no actual Raydium CLMM CPI yet (placeholder math
//     only) — same class as earn-vault C-02 harvest (61407a3); should be
//     hard-disabled until ADR 0009 rebuild lands real CLMM integration
// (NB: pomm's emergency_withdraw correctly REQUIRES paused — line 113 — so
// the H-03 'withdraw-locked-during-pause' pattern from earn-vault does NOT
// apply here. pomm has no plain user-facing withdraw to lock out.)
//
// Mainnet deploy gated on (per #22 EPIC):
//   1. ADR 0009 full implementation (Raydium CLMM CPI, oracle hardening,
//      multisig governance + 7d timelock, EMA tracking)
//   2. OtterSec audit + critical/high findings remediated
//   3. Cayman Foundation incorporation
//   4. Real program keypair generated by Squads multisig
// L-01 ADR 0018 compile_error guard (mirrors ping-token 2bd1c24).
#[cfg(all(feature = "mainnet-ready", not(feature = "audit-passed")))]
compile_error!(
    "pomm: mainnet-ready feature requires audit-passed feature \
     (set only AFTER OtterSec audit completes per #22 EPIC + ADR 0018)"
);
declare_id!("PommProgr4mPubKeyP1ace00011111111111111111");

const EMA_BAND_BPS: u16 = 1_500;
const MAX_PER_DAY_DEPLOYED_BPS: u16 = 50;

#[program]
pub mod pomm {
    use super::*;

    pub fn initialize_treasury(
        ctx: Context<InitializeTreasury>,
        squads_multisig: Pubkey,
    ) -> Result<()> {
        let treasury = &mut ctx.accounts.treasury;
        treasury.authority = squads_multisig;
        treasury.usdc_mint = ctx.accounts.usdc_mint.key();
        treasury.usdc_vault = ctx.accounts.usdc_vault.key();
        treasury.total_usdc = 0;
        treasury.deployed_usdc = 0;
        treasury.collected_fees_lifetime = 0;
        treasury.is_paused = false;
        treasury.bump = ctx.bumps.treasury;
        // C-04: initialize 24h cap-window accountant
        treasury.window_start_ts = Clock::get()?.unix_timestamp;
        treasury.deployed_in_window = 0;

        // M-class fix cross-applied from internal-swap M-04 (eace98f):
        // emit creation event so indexers don't need to crawl program
        // accounts to detect a new Treasury.
        emit!(TreasuryInitialized {
            treasury: treasury.key(),
            authority: treasury.authority,
            usdc_mint: treasury.usdc_mint,
            usdc_vault: treasury.usdc_vault,
            window_start_ts: treasury.window_start_ts,
            bump: treasury.bump,
        });
        Ok(())
    }

    pub fn deposit_usdc(ctx: Context<DepositUsdc>, amount: u64) -> Result<()> {
        require!(!ctx.accounts.treasury.is_paused, PommError::Paused);
        require!(amount > 0, PommError::ZeroAmount);

        token_interface::transfer_checked(
            ctx.accounts.transfer_ctx(),
            amount,
            ctx.accounts.usdc_mint.decimals,
        )?;

        let treasury = &mut ctx.accounts.treasury;
        treasury.total_usdc = treasury.total_usdc.checked_add(amount).ok_or(PommError::MathOverflow)?;

        emit!(DepositEvent {
            treasury: treasury.key(),
            depositor: ctx.accounts.depositor.key(),
            amount,
        });
        Ok(())
    }

    /// SCAFFOLD-LIFETIME DEFENSIVE NO-OP closing pomm Critical findings
    /// C-01, C-02, C-03 in one stroke (#22 c.4527297108):
    ///   - C-01: original mint_lp_position did NO actual Raydium CLMM CPI,
    ///     just bumped a counter — operator-trust hole, same class as
    ///     earn-vault C-02 harvest (closed in 61407a3)
    ///   - C-02: oracle_price_x64 + ema_price_x64 were caller-supplied with
    ///     no Pyth/Switchboard verification — the band check is theater
    ///     because the authority controls both inputs
    ///   - C-03: no on-chain EMA state, no per-tick accumulator, no
    ///     staleness guard — the "7-day EMA" exists only in the ADR
    ///
    /// All three are rebuild-scope (ADR 0009 requires Pyth integration,
    /// real Raydium CLMM CPI, and an on-chain EMA accumulator PDA). Until
    /// that rebuild lands, mint_lp_position is hard-disabled — every call
    /// reverts. C-04 (daily cap accountant in 1f995d7) + window state
    /// stay in the struct so the rebuild can layer on them without further
    /// data migration. NB: total_usdc / deployed_in_window / window_start_ts
    /// remain on the Treasury struct.
    pub fn mint_lp_position(
        _ctx: Context<MintLpPosition>,
        _amount: u64,
        _oracle_price_x64: u128,
        _ema_price_x64: u128,
    ) -> Result<()> {
        err!(PommError::DeployToClmmDisabledUntilRebuild)
    }

    /// SCAFFOLD-LIFETIME DEFENSIVE NO-OP. H-01 fix (#22 c.4527297108) —
    /// original collect_fees accepted caller-supplied `fees: u64` with zero
    /// verification, so the authority could call collect_fees(any) and
    /// inflate collected_fees_lifetime arbitrarily for downstream accounting
    /// abuse. Same operator-trust hole class as earn-vault C-02 (closed by
    /// hard-disable in 61407a3).
    ///
    /// Until the ADR 0009 rebuild lands real CLMM CPI that READS fees from
    /// the Raydium pool's actual collected amounts, collect_fees is hard-
    /// disabled. The attack is now PHYSICALLY IMPOSSIBLE — no caller can
    /// advance the collected_fees_lifetime counter via this path.
    pub fn collect_fees(_ctx: Context<CollectFees>, _fees: u64) -> Result<()> {
        err!(PommError::CollectFeesDisabledUntilRebuild)
    }

    pub fn set_paused(ctx: Context<AdminTreasury>, paused: bool) -> Result<()> {
        ctx.accounts.treasury.is_paused = paused;
        emit!(PausedEvent { treasury: ctx.accounts.treasury.key(), paused });
        Ok(())
    }

    /// Rotate the treasury authority to a new pubkey. H-03 fix
    /// (per #22 c.4527297108). Mirrors earn-vault 2d89968 +
    /// ping-token f1cfab4 + internal-swap 23d62cc. Same migration-to-
    /// multisig pattern across all 4 Phase-2 Anchor programs.
    pub fn rotate_authority(
        ctx: Context<AdminTreasury>,
        new_authority: Pubkey,
    ) -> Result<()> {
        require!(new_authority != Pubkey::default(), PommError::ZeroPubkey);
        let old_authority = ctx.accounts.treasury.authority;
        ctx.accounts.treasury.authority = new_authority;
        emit!(AuthorityRotated {
            treasury: ctx.accounts.treasury.key(),
            old_authority,
            new_authority,
        });
        Ok(())
    }

    pub fn emergency_withdraw(ctx: Context<EmergencyWithdraw>, amount: u64) -> Result<()> {
        require!(ctx.accounts.treasury.is_paused, PommError::EmergencyRequiresPause);

        // H-02 fix (per #22 c.4527297108): signer seeds bind to usdc_mint
        // matching the per-mint Treasury PDA. Same pattern as earn-vault C-04
        // (f7ea54f).
        let usdc_mint_key = ctx.accounts.treasury.usdc_mint;
        let seeds = &[
            b"treasury".as_ref(),
            usdc_mint_key.as_ref(),
            &[ctx.accounts.treasury.bump],
        ];
        let signer = &[&seeds[..]];
        token_interface::transfer_checked(
            ctx.accounts.transfer_ctx().with_signer(signer),
            amount,
            ctx.accounts.usdc_mint.decimals,
        )?;

        let treasury = &mut ctx.accounts.treasury;
        treasury.total_usdc = treasury.total_usdc.checked_sub(amount).ok_or(PommError::MathOverflow)?;
        emit!(EmergencyWithdrawEvent { treasury: treasury.key(), amount });
        Ok(())
    }
}

fn price_within_band(price_x64: u128, ema_x64: u128) -> bool {
    if ema_x64 == 0 { return false; }
    let band = ema_x64.checked_mul(EMA_BAND_BPS as u128).and_then(|x| x.checked_div(10_000)).unwrap_or(0);
    let lower = ema_x64.saturating_sub(band);
    let upper = ema_x64.saturating_add(band);
    price_x64 >= lower && price_x64 <= upper
}

#[account]
pub struct Treasury {
    pub authority: Pubkey,
    pub usdc_mint: Pubkey,
    pub usdc_vault: Pubkey,
    pub total_usdc: u64,
    pub deployed_usdc: u64,
    pub collected_fees_lifetime: u64,
    pub is_paused: bool,
    pub bump: u8,
    // C-04 fix: 24h rolling deploy-cap accountant. Reset when 86_400 sec
    // since window_start_ts elapses. Without this the original "0.5%/day"
    // cap was bypassable by repeated calls.
    pub window_start_ts: i64,
    pub deployed_in_window: u64,
}

impl Treasury {
    // 8 disc + 3*32 keys + 3*8 u64 + 1 bool + 1 bump + 8 i64 + 8 u64 = 162
    pub const LEN: usize = 8 + 32 * 3 + 8 * 3 + 1 + 1 + 8 + 8;
}

#[derive(Accounts)]
pub struct InitializeTreasury<'info> {
    #[account(mut)]
    pub payer: Signer<'info>,
    #[account(init, payer = payer, space = Treasury::LEN, seeds = [b"treasury", usdc_mint.key().as_ref()], bump)]
    pub treasury: Account<'info, Treasury>,
    pub usdc_mint: InterfaceAccount<'info, Mint>,
    // H-05 fix (per #22 c.4527297108): bind usdc_vault to (treasury PDA owner,
    // expected mint, no close authority). Same shape as earn-vault C-03
    // (2c35aee) + internal-swap C4 (564e6af).
    #[account(
        constraint = usdc_vault.owner == treasury.key() @ PommError::WrongVaultOwner,
        constraint = usdc_vault.mint == usdc_mint.key() @ PommError::WrongVaultMint,
        constraint = usdc_vault.close_authority.is_none() @ PommError::VaultMustNotBeCloseable,
    )]
    pub usdc_vault: InterfaceAccount<'info, TokenAccount>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct DepositUsdc<'info> {
    #[account(mut)]
    pub depositor: Signer<'info>,
    #[account(mut, seeds = [b"treasury", usdc_mint.key().as_ref()], bump = treasury.bump)]
    pub treasury: Account<'info, Treasury>,
    pub usdc_mint: InterfaceAccount<'info, Mint>,
    #[account(mut)]
    pub depositor_usdc_ata: InterfaceAccount<'info, TokenAccount>,
    #[account(mut, address = treasury.usdc_vault)]
    pub usdc_vault: InterfaceAccount<'info, TokenAccount>,
    pub token_program: Interface<'info, TokenInterface>,
}

impl<'info> DepositUsdc<'info> {
    fn transfer_ctx(&self) -> CpiContext<'_, '_, '_, 'info, TransferChecked<'info>> {
        CpiContext::new(self.token_program.to_account_info(), TransferChecked {
            from: self.depositor_usdc_ata.to_account_info(),
            mint: self.usdc_mint.to_account_info(),
            to: self.usdc_vault.to_account_info(),
            authority: self.depositor.to_account_info(),
        })
    }
}

#[derive(Accounts)]
pub struct MintLpPosition<'info> {
    #[account(address = treasury.authority)]
    pub authority: Signer<'info>,
    #[account(mut, seeds = [b"treasury", usdc_mint.key().as_ref()], bump = treasury.bump)]
    pub treasury: Account<'info, Treasury>,
}

#[derive(Accounts)]
pub struct CollectFees<'info> {
    #[account(address = treasury.authority)]
    pub authority: Signer<'info>,
    #[account(mut, seeds = [b"treasury", usdc_mint.key().as_ref()], bump = treasury.bump)]
    pub treasury: Account<'info, Treasury>,
}

#[derive(Accounts)]
pub struct AdminTreasury<'info> {
    #[account(address = treasury.authority)]
    pub authority: Signer<'info>,
    #[account(mut, seeds = [b"treasury", usdc_mint.key().as_ref()], bump = treasury.bump)]
    pub treasury: Account<'info, Treasury>,
}

#[derive(Accounts)]
pub struct EmergencyWithdraw<'info> {
    #[account(address = treasury.authority)]
    pub authority: Signer<'info>,
    #[account(mut, seeds = [b"treasury", usdc_mint.key().as_ref()], bump = treasury.bump)]
    pub treasury: Account<'info, Treasury>,
    pub usdc_mint: InterfaceAccount<'info, Mint>,
    #[account(mut, address = treasury.usdc_vault)]
    pub usdc_vault: InterfaceAccount<'info, TokenAccount>,
    /// H-04 fix (per #22 c.4527297108): emergency_withdraw destination
    /// MUST be owned by treasury.authority (Squads multisig in prod), not
    /// any caller-chosen wallet. Without this, a single-signer pause-and-
    /// drain attack works: pause treasury → emergency_withdraw to attacker
    /// ATA → unpause. ADR 0009 says "Multisig can only pause" — this
    /// constraint enforces that even an emergency exit can only route
    /// funds back to the authority's control.
    #[account(
        mut,
        constraint = destination_ata.owner == treasury.authority @ PommError::WrongEmergencyDestination,
        constraint = destination_ata.mint == usdc_mint.key() @ PommError::WrongVaultMint,
    )]
    pub destination_ata: InterfaceAccount<'info, TokenAccount>,
    pub token_program: Interface<'info, TokenInterface>,
}

impl<'info> EmergencyWithdraw<'info> {
    fn transfer_ctx(&self) -> CpiContext<'_, '_, '_, 'info, TransferChecked<'info>> {
        CpiContext::new(self.token_program.to_account_info(), TransferChecked {
            from: self.usdc_vault.to_account_info(),
            mint: self.usdc_mint.to_account_info(),
            to: self.destination_ata.to_account_info(),
            authority: self.treasury.to_account_info(),
        })
    }
}

#[event]
pub struct DepositEvent {
    pub treasury: Pubkey,
    pub depositor: Pubkey,
    pub amount: u64,
}

#[event]
pub struct LpMintEvent {
    pub treasury: Pubkey,
    pub amount: u64,
    pub oracle_price_x64: u128,
}

#[event]
pub struct FeesCollected {
    pub treasury: Pubkey,
    pub amount: u64,
}

#[event]
pub struct PausedEvent {
    pub treasury: Pubkey,
    pub paused: bool,
}

#[event]
pub struct EmergencyWithdrawEvent {
    pub treasury: Pubkey,
    pub amount: u64,
}

#[event]
pub struct AuthorityRotated {
    pub treasury: Pubkey,
    pub old_authority: Pubkey,
    pub new_authority: Pubkey,
}

#[event]
pub struct TreasuryInitialized {
    pub treasury: Pubkey,
    pub authority: Pubkey,
    pub usdc_mint: Pubkey,
    pub usdc_vault: Pubkey,
    pub window_start_ts: i64,
    pub bump: u8,
}

#[error_code]
pub enum PommError {
    #[msg("Treasury is paused")]
    Paused,
    #[msg("Amount must be > 0")]
    ZeroAmount,
    #[msg("Oracle price outside EMA band")]
    PriceOutOfBand,
    #[msg("Per-day deployment cap exceeded")]
    DailyCapExceeded,
    #[msg("Emergency withdraw requires paused state")]
    EmergencyRequiresPause,
    #[msg("Arithmetic overflow")]
    MathOverflow,
    #[msg("usdc_vault.owner must equal the treasury PDA")]
    WrongVaultOwner,
    #[msg("usdc_vault.mint must equal the usdc_mint passed to initialize_treasury")]
    WrongVaultMint,
    #[msg("usdc_vault.close_authority must be None (vault must not be closeable)")]
    VaultMustNotBeCloseable,
    #[msg("emergency_withdraw destination must be owned by treasury.authority (multisig)")]
    WrongEmergencyDestination,
    #[msg("New authority cannot be the zero pubkey")]
    ZeroPubkey,
    #[msg("collect_fees disabled in scaffold; full rebuild per ADR 0009 (real CLMM fee-read CPI) required first")]
    CollectFeesDisabledUntilRebuild,
    #[msg("mint_lp_position disabled in scaffold; full rebuild per ADR 0009 (Pyth oracle + on-chain EMA + Raydium CLMM CPI) required first")]
    DeployToClmmDisabledUntilRebuild,
}
