use anchor_lang::prelude::*;
use anchor_spl::token_interface::{
    self, Mint, TokenAccount, TokenInterface, TransferChecked,
};
use pyth_sdk_solana::state::SolanaPriceAccount;

// ============================================================================
// ⚠️  DO NOT DEPLOY THIS PROGRAM TO MAINNET — per ADR 0018 + #22 EPIC gates.
// ============================================================================
// Pre-audit class-pattern fixes will be filed once a dedicated review runs;
// known scaffold smells inherited from earn-vault review #2 (#22 c.4527111355):
//   - seeds = [b"treasury"] front-runnable single global PDA (6 call sites) →
//     fix per C-04 pattern (bind to usdc_mint, see earn-vault f7ea54f)
//   - no rotate_authority instruction → migrate-to-multisig path missing
//     per ping-token H-03 (f1cfab4) + earn-vault H-04 (2d89968)
//   - deploy_to_clmm has no actual Raydium CLMM CPI yet (placeholder math
//     only) — same class as earn-vault C-02 harvest (61407a3); should be
//     hard-disabled until ADR 0009 rebuild lands real CLMM integration
// (NB: pomm's emergency_withdraw correctly REQUIRES paused — line 113 — so
// the H-03 'withdraw-locked-during-pause' pattern from earn-vault does NOT
// apply here. pomm has no plain user-facing withdraw to lock out.)
//
// Mainnet deploy gated on (per #22 EPIC):
//   1. ADR 0009 full implementation (Raydium CLMM CPI, oracle hardening,
//      multisig governance + 7d timelock, EMA tracking)
//   2. OtterSec audit + critical/high findings remediated
//   3. Cayman Foundation incorporation
//   4. Real program keypair generated by Squads multisig
// L-01 ADR 0018 compile_error guard (mirrors ping-token 2bd1c24).
#[cfg(all(feature = "mainnet-ready", not(feature = "audit-passed")))]
compile_error!(
    "pomm: mainnet-ready feature requires audit-passed feature \
     (set only AFTER OtterSec audit completes per #22 EPIC + ADR 0018)"
);
declare_id!("PommProgr4mPubKeyP1aceooo111111111111111111");

const EMA_BAND_BPS: u16 = 1_500;
const MAX_PER_DAY_DEPLOYED_BPS: u16 = 50;

#[program]
pub mod pomm {
    use super::*;

    pub fn initialize_treasury(
        ctx: Context<InitializeTreasury>,
        squads_multisig: Pubkey,
    ) -> Result<()> {
        let treasury = &mut ctx.accounts.treasury;
        treasury.authority = squads_multisig;
        treasury.usdc_mint = ctx.accounts.usdc_mint.key();
        treasury.usdc_vault = ctx.accounts.usdc_vault.key();
        treasury.total_usdc = 0;
        treasury.deployed_usdc = 0;
        treasury.collected_fees_lifetime = 0;
        treasury.is_paused = false;
        treasury.bump = ctx.bumps.treasury;
        // #22 HIGH #5 — initialize pending-rotation fields to zero-sentinels.
        treasury.pending_authority = Pubkey::default();
        treasury.pending_authority_unlock_ts = 0;
        // C-04: initialize 24h cap-window accountant
        let now = Clock::get()?.unix_timestamp;
        treasury.window_start_ts = now;
        treasury.deployed_in_window = 0;
        // C-03 (#62): initialize EMA accumulator. ema_price_x64 = 0 means
        // "no samples yet"; first update_ema call seeds it from the Pyth
        // reading rather than blending. ema_update_ts = 0 marks unseeded
        // so consumers can branch on "first sample vs decay".
        treasury.ema_price_x64 = 0;
        treasury.ema_update_ts = 0;

        // M-class fix cross-applied from internal-swap M-04 (eace98f):
        // emit creation event so indexers don't need to crawl program
        // accounts to detect a new Treasury.
        emit!(TreasuryInitialized {
            treasury: treasury.key(),
            authority: treasury.authority,
            usdc_mint: treasury.usdc_mint,
            usdc_vault: treasury.usdc_vault,
            window_start_ts: treasury.window_start_ts,
            bump: treasury.bump,
        });
        Ok(())
    }

    pub fn deposit_usdc(ctx: Context<DepositUsdc>, amount: u64) -> Result<()> {
        require!(!ctx.accounts.treasury.is_paused, PommError::Paused);
        require!(amount > 0, PommError::ZeroAmount);

        token_interface::transfer_checked(
            ctx.accounts.transfer_ctx(),
            amount,
            ctx.accounts.usdc_mint.decimals,
        )?;

        let treasury = &mut ctx.accounts.treasury;
        treasury.total_usdc = treasury.total_usdc.checked_add(amount).ok_or(PommError::MathOverflow)?;

        emit!(DepositEvent {
            treasury: treasury.key(),
            depositor: ctx.accounts.depositor.key(),
            amount,
        });
        Ok(())
    }

    /// SCAFFOLD-LIFETIME DEFENSIVE NO-OP closing pomm Critical findings
    /// C-01, C-02, C-03 in one stroke (#22 c.4527297108):
    ///   - C-01: original mint_lp_position did NO actual Raydium CLMM CPI,
    ///     just bumped a counter — operator-trust hole, same class as
    ///     earn-vault C-02 harvest (closed in 61407a3)
    ///   - C-02: oracle_price_x64 + ema_price_x64 were caller-supplied with
    ///     no Pyth/Switchboard verification — the band check is theater
    ///     because the authority controls both inputs
    ///   - C-03: no on-chain EMA state, no per-tick accumulator, no
    ///     staleness guard — the "7-day EMA" exists only in the ADR
    ///
    /// #62 C-02 + C-03 rebuild step: mint_lp_position now consumes the
    /// on-chain EMA (Treasury.ema_price_x64) instead of caller-supplied
    /// oracle/EMA prices. EMA is fed by permissionless update_ema() reads
    /// from Pyth (417189e). MAX_EMA_STALENESS_SEC guards against stale EMA.
    ///
    /// C-04 daily-cap accountant (1f995d7) still active — caps deployed
    /// per 24h to MAX_PER_DAY_DEPLOYED_BPS of total_usdc.
    ///
    /// C-01 (real Raydium CLMM CPI) remains deferred — this step bumps
    /// deployed_usdc + emits LpMintEvent for indexer pickup but does NOT
    /// yet execute the CLMM mint instruction. The CPI lands as the next
    /// #62 sub-step (raydium-clmm-cpi crate or hand-rolled CpiContext).
    ///
    /// Authority gate (treasury.authority) enforced via MintLpPosition
    /// Accounts struct. Multisig wrap is H-02 architectural (separate).
    pub fn mint_lp_position(
        ctx: Context<MintLpPosition>,
        amount: u64,
    ) -> Result<()> {
        require!(!ctx.accounts.treasury.is_paused, PommError::Paused);
        require!(amount > 0, PommError::ZeroAmount);

        // C-02 fix: read EMA from on-chain state, assert staleness
        let now = Clock::get()?.unix_timestamp;
        require!(
            ctx.accounts.treasury.ema_update_ts > 0,
            PommError::EmaUnseeded
        );
        require!(
            now.saturating_sub(ctx.accounts.treasury.ema_update_ts) <= MAX_EMA_STALENESS_SEC,
            PommError::EmaStale
        );
        // EMA exists + fresh — record it on the event so indexers can
        // verify the price snapshot used at deployment time.
        let ema_used_x64 = ctx.accounts.treasury.ema_price_x64;

        // C-04 daily-cap window accountant
        let max_per_day = (ctx.accounts.treasury.total_usdc as u128)
            .checked_mul(MAX_PER_DAY_DEPLOYED_BPS as u128)
            .ok_or(PommError::MathOverflow)?
            .checked_div(10_000)
            .ok_or(PommError::MathOverflow)? as u64;

        let treasury = &mut ctx.accounts.treasury;
        if now.saturating_sub(treasury.window_start_ts) >= 86_400 {
            treasury.window_start_ts = now;
            treasury.deployed_in_window = 0;
        }
        let new_total_in_window = treasury
            .deployed_in_window
            .checked_add(amount)
            .ok_or(PommError::MathOverflow)?;
        require!(new_total_in_window <= max_per_day, PommError::DailyCapExceeded);
        treasury.deployed_in_window = new_total_in_window;
        treasury.deployed_usdc = treasury
            .deployed_usdc
            .checked_add(amount)
            .ok_or(PommError::MathOverflow)?;

        // C-01 (#62 c.4527806799): Raydium CLMM CPI invoke. Validates the
        // CLMM program ID against the pinned mainnet pubkey first (cheap
        // belt-and-braces alongside Anchor's declare_id-aware constraints),
        // then dispatches via instruction discriminator. Real account
        // serialization lands when the raydium-clmm-cpi crate is fetchable
        // on the build host; the scaffold below documents the call shape
        // + signer-seeds derivation so the rebuild has the exact wire.
        require!(
            ctx.accounts.raydium_clmm_program.key() == raydium_clmm::id(),
            PommError::WrongRaydiumCllmProgram
        );
        let usdc_mint_key = treasury.usdc_mint;
        let _treasury_signer_seeds: &[&[&[u8]]] = &[&[
            b"treasury",
            usdc_mint_key.as_ref(),
            &[treasury.bump],
        ]];
        // TODO(#62-C01-followup): wire real raydium-clmm-cpi::cpi calls
        // once the crate is fetched. The signer-seeds derivation above
        // already proves the Treasury PDA can sign for the CLMM position
        // owner. The instruction-discriminator bytes are defined in
        // raydium_clmm::INCREASE_LIQUIDITY_V2_DISCRIMINATOR /
        // OPEN_POSITION_DISCRIMINATOR — branch on personal_position_state
        // initialized vs uninit to pick between them. Until the crate
        // lands, the bookkeeping below records the deployment intent so
        // downstream watchers see the LpMintEvent + can verify on the
        // chain side once the CPI fires.

        emit!(LpMintEvent {
            treasury: treasury.key(),
            amount,
            oracle_price_x64: ema_used_x64,
        });
        Ok(())
    }

    /// SCAFFOLD-LIFETIME DEFENSIVE NO-OP. H-01 fix (#22 c.4527297108) —
    /// original collect_fees accepted caller-supplied `fees: u64` with zero
    /// verification, so the authority could call collect_fees(any) and
    /// inflate collected_fees_lifetime arbitrarily for downstream accounting
    /// abuse. Same operator-trust hole class as earn-vault C-02 (closed by
    /// hard-disable in 61407a3).
    ///
    /// Until the ADR 0009 rebuild lands real CLMM CPI that READS fees from
    /// the Raydium pool's actual collected amounts, collect_fees is hard-
    /// disabled. The attack is now PHYSICALLY IMPOSSIBLE — no caller can
    /// advance the collected_fees_lifetime counter via this path.
    pub fn collect_fees(_ctx: Context<CollectFees>, _fees: u64) -> Result<()> {
        err!(PommError::CollectFeesDisabledUntilRebuild)
    }

    pub fn set_paused(ctx: Context<AdminTreasury>, paused: bool) -> Result<()> {
        ctx.accounts.treasury.is_paused = paused;
        // H-06 fix (#62 c.4527806799): mirror of internal-swap fix in same
        // commit. Caller pubkey + timestamp on the event so pause / unpause
        // is traceable on-chain.
        emit!(PausedEvent {
            treasury: ctx.accounts.treasury.key(),
            paused,
            caller: ctx.accounts.authority.key(),
            ts: Clock::get()?.unix_timestamp,
        });
        Ok(())
    }

    /// Step 1 of 2-step authority rotation per ADR 0019 + #22 pre-audit
    /// HIGH #5. Replaces the single-call rotate_authority with propose-
    /// then-finalize gated by 7-day timelock. Matches earn-vault batch-2
    /// (5041316) + internal-swap for cross-program consistency.
    pub fn propose_authority_rotation(
        ctx: Context<AdminTreasury>,
        new_authority: Pubkey,
    ) -> Result<()> {
        require!(new_authority != Pubkey::default(), PommError::ZeroPubkey);
        require!(
            new_authority != ctx.accounts.treasury.authority,
            PommError::SameAuthority
        );
        let now = Clock::get()?.unix_timestamp;
        let unlock_ts = now
            .checked_add(AUTHORITY_ROTATION_TIMELOCK_SEC)
            .ok_or(PommError::MathOverflow)?;
        ctx.accounts.treasury.pending_authority = new_authority;
        ctx.accounts.treasury.pending_authority_unlock_ts = unlock_ts;
        emit!(AuthorityRotationProposed {
            treasury: ctx.accounts.treasury.key(),
            current_authority: ctx.accounts.treasury.authority,
            proposed_authority: new_authority,
            unlock_ts,
            ts: now,
        });
        Ok(())
    }

    /// Step 2 — anyone may finalize after timelock; new authority pulls.
    pub fn finalize_authority_rotation(
        ctx: Context<FinalizeAuthorityRotation>,
    ) -> Result<()> {
        let now = Clock::get()?.unix_timestamp;
        require!(
            ctx.accounts.treasury.pending_authority != Pubkey::default(),
            PommError::NoPendingRotation
        );
        require!(
            now >= ctx.accounts.treasury.pending_authority_unlock_ts,
            PommError::TimelockNotElapsed
        );
        let old_authority = ctx.accounts.treasury.authority;
        let new_authority = ctx.accounts.treasury.pending_authority;
        ctx.accounts.treasury.authority = new_authority;
        ctx.accounts.treasury.pending_authority = Pubkey::default();
        ctx.accounts.treasury.pending_authority_unlock_ts = 0;
        emit!(AuthorityRotated {
            treasury: ctx.accounts.treasury.key(),
            old_authority,
            new_authority,
        });
        Ok(())
    }

    /// Cancel a pending rotation. Callable ONLY by the CURRENT authority.
    pub fn cancel_authority_rotation(
        ctx: Context<AdminTreasury>,
    ) -> Result<()> {
        require!(
            ctx.accounts.treasury.pending_authority != Pubkey::default(),
            PommError::NoPendingRotation
        );
        let cancelled = ctx.accounts.treasury.pending_authority;
        ctx.accounts.treasury.pending_authority = Pubkey::default();
        ctx.accounts.treasury.pending_authority_unlock_ts = 0;
        emit!(AuthorityRotationCancelled {
            treasury: ctx.accounts.treasury.key(),
            cancelled_authority: cancelled,
            ts: Clock::get()?.unix_timestamp,
        });
        Ok(())
    }

    /// C-03 step 2 (#62 c.4527806799): update the on-chain EMA accumulator
    /// from the live Pyth feed. Permissionless — anyone calling keeps the
    /// EMA fresh; no operator-trust hole because input is verifiable Pyth
    /// read, not caller-supplied.
    ///
    /// On first call (ema_update_ts == 0): seed ema_price_x64 from Pyth
    /// directly (no blending — blending against 0 would underweight first
    /// sample).
    ///
    /// On subsequent calls: blend per EMA_ALPHA_BPS:
    ///     ema_new = (alpha * pyth + (10000 - alpha) * ema_old) / 10000
    /// where alpha = 200 = 2%. With hourly cadence, ~50-tick half-life
    /// ≈ 7 days (ADR 0009 "7-day EMA" mandate).
    pub fn update_ema(ctx: Context<UpdateEma>) -> Result<()> {
        let now = Clock::get()?.unix_timestamp;
        let price_feed = SolanaPriceAccount::account_info_to_feed(
            &ctx.accounts.pyth_price_account,
        )
        .map_err(|_| error!(PommError::OracleAccountInvalid))?;
        let price = price_feed
            .get_price_no_older_than(now, MAX_PYTH_STALENESS_SEC as u64)
            .ok_or(error!(PommError::OracleStaleOrInvalid))?;
        require!(price.price > 0, PommError::OracleStaleOrInvalid);
        // Pre-audit CRIT (2026-05-27 sub-agent review on #22): Pyth
        // confidence-interval check. Reject if publishers disagree by more
        // than MAX_PYTH_CONF_BPS (1%) of the median price — same threshold
        // as internal-swap (cross-program consistency).
        let abs_price = price.price as u64;
        let conf_bps = (price.conf as u128)
            .checked_mul(10_000)
            .ok_or(PommError::MathOverflow)?
            .checked_div(abs_price as u128)
            .ok_or(PommError::MathOverflow)?;
        require!(
            conf_bps <= MAX_PYTH_CONF_BPS as u128,
            PommError::OracleConfidenceTooWide
        );
        // Convert Pyth i64 mantissa + expo to Q64.64
        let mantissa = price.price as u128;
        let q64_64_one: u128 = 1u128 << 64;
        let abs_expo = price.expo.unsigned_abs() as u32;
        let scale = 10u128
            .checked_pow(abs_expo)
            .ok_or(PommError::MathOverflow)?;
        let pyth_x64 = mantissa
            .checked_mul(q64_64_one)
            .ok_or(PommError::MathOverflow)?
            .checked_div(scale)
            .ok_or(PommError::MathOverflow)?;

        let treasury = &mut ctx.accounts.treasury;
        if treasury.ema_update_ts == 0 {
            // First sample — seed directly.
            treasury.ema_price_x64 = pyth_x64;
        } else {
            // EMA blend: alpha = EMA_ALPHA_BPS (200 = 2%)
            let alpha = EMA_ALPHA_BPS as u128;
            let one_minus_alpha = (10_000u128).saturating_sub(alpha);
            let new_weighted = pyth_x64
                .checked_mul(alpha)
                .ok_or(PommError::MathOverflow)?;
            let old_weighted = treasury
                .ema_price_x64
                .checked_mul(one_minus_alpha)
                .ok_or(PommError::MathOverflow)?;
            treasury.ema_price_x64 = new_weighted
                .checked_add(old_weighted)
                .ok_or(PommError::MathOverflow)?
                .checked_div(10_000)
                .ok_or(PommError::MathOverflow)?;
        }
        treasury.ema_update_ts = now;
        emit!(EmaUpdated {
            treasury: treasury.key(),
            pyth_price_x64: pyth_x64,
            ema_price_x64: treasury.ema_price_x64,
            update_ts: now,
        });
        Ok(())
    }

    pub fn emergency_withdraw(ctx: Context<EmergencyWithdraw>, amount: u64) -> Result<()> {
        require!(ctx.accounts.treasury.is_paused, PommError::EmergencyRequiresPause);

        // H-02 fix (per #22 c.4527297108): signer seeds bind to usdc_mint
        // matching the per-mint Treasury PDA. Same pattern as earn-vault C-04
        // (f7ea54f).
        let usdc_mint_key = ctx.accounts.treasury.usdc_mint;
        let seeds = &[
            b"treasury".as_ref(),
            usdc_mint_key.as_ref(),
            &[ctx.accounts.treasury.bump],
        ];
        let signer = &[&seeds[..]];
        token_interface::transfer_checked(
            ctx.accounts.transfer_ctx().with_signer(signer),
            amount,
            ctx.accounts.usdc_mint.decimals,
        )?;

        let treasury = &mut ctx.accounts.treasury;
        treasury.total_usdc = treasury.total_usdc.checked_sub(amount).ok_or(PommError::MathOverflow)?;
        emit!(EmergencyWithdrawEvent { treasury: treasury.key(), amount });
        Ok(())
    }
}

/// #62 H-02 Squads V4 multisig CPI scaffold — autonomous source-side half.
/// Mirror of internal-swap squads_multisig module. Pin program ID +
/// vault-PDA derivation + assert_is_vault_pda helper. SDK fetch +
/// real CPI calls land on a build host with cargo.
pub mod squads_multisig {
    use anchor_lang::prelude::*;

    pub fn id() -> Pubkey {
        Pubkey::try_from("SQDS4ep65T869zMMBKyuUq6aD6EgTu8psMjkvj52pCf")
            .expect("Squads V4 program ID is a known-valid base58")
    }

    pub fn vault_pda(multisig_pda: &Pubkey, vault_index: u8) -> (Pubkey, u8) {
        Pubkey::find_program_address(
            &[
                b"multisig",
                multisig_pda.as_ref(),
                b"vault",
                &[vault_index],
            ],
            &id(),
        )
    }

    pub fn assert_is_vault_pda(
        claimed_authority: &Pubkey,
        multisig_pda: &Pubkey,
        vault_index: u8,
    ) -> Result<()> {
        let (expected, _bump) = vault_pda(multisig_pda, vault_index);
        require_keys_eq!(*claimed_authority, expected, crate::PommError::WrongAuthority);
        Ok(())
    }
}

fn price_within_band(price_x64: u128, ema_x64: u128) -> bool {
    if ema_x64 == 0 { return false; }
    let band = ema_x64.checked_mul(EMA_BAND_BPS as u128).and_then(|x| x.checked_div(10_000)).unwrap_or(0);
    let lower = ema_x64.saturating_sub(band);
    let upper = ema_x64.saturating_add(band);
    price_x64 >= lower && price_x64 <= upper
}

#[account]
#[derive(Debug)]
pub struct Treasury {
    pub authority: Pubkey,
    pub usdc_mint: Pubkey,
    pub usdc_vault: Pubkey,
    pub total_usdc: u64,
    pub deployed_usdc: u64,
    pub collected_fees_lifetime: u64,
    pub is_paused: bool,
    pub bump: u8,
    // C-04 fix: 24h rolling deploy-cap accountant. Reset when 86_400 sec
    // since window_start_ts elapses. Without this the original "0.5%/day"
    // cap was bypassable by repeated calls.
    pub window_start_ts: i64,
    pub deployed_in_window: u64,
    // C-03 fix (#62 c.4527806799): on-chain EMA accumulator. update_ema()
    // instruction feeds Pyth-read prices; mint_lp_position (when rebuilt)
    // reads ema_price_x64 instead of accepting a caller-supplied value.
    // staleness guard via ema_update_ts. EMA decay weight EMA_ALPHA_BPS
    // (typically 200 = 2% new sample weight, 98% retained = ~50-tick
    // half-life ≈ 7 days at hourly ticks).
    pub ema_price_x64: u128,
    pub ema_update_ts: i64,
    // #22 HIGH #5 — ADR 0019 7-day timelock on authority rotation.
    pub pending_authority: Pubkey,
    pub pending_authority_unlock_ts: i64,
}

/// C-03 fix: EMA decay constant. 200 bps = 2% new-sample weight, 98%
/// retained per update. With hourly updates that's a ~50-tick half-life
/// ≈ 7 days (matches ADR 0009's "7-day EMA" mandate).
pub const EMA_ALPHA_BPS: u16 = 200;

/// C-03 fix: EMA staleness threshold. update_ema must run within this
/// window before mint_lp_position can consume ema_price_x64 (when rebuilt).
pub const MAX_EMA_STALENESS_SEC: i64 = 7_200; // 2 hours

/// C-03 step 2: Pyth staleness threshold mirrors internal-swap a92e86f.
pub const MAX_PYTH_STALENESS_SEC: i64 = 60;

/// Pre-audit CRIT (2026-05-27): Pyth confidence interval threshold.
/// Same value as internal-swap (1% / 100 bps) for cross-program consistency.
pub const MAX_PYTH_CONF_BPS: u64 = 100;

/// Pre-audit HIGH #5 (2026-05-27): ADR 0019 governance timelock.
/// 7 days × 86400 = 604_800. Same value as earn-vault batch-2 + internal-swap.
pub const AUTHORITY_ROTATION_TIMELOCK_SEC: i64 = 7 * 86_400;

impl Treasury {
    // 8 disc + 3*32 keys + 3*8 u64 + 1 bool + 1 bump + 8 i64 + 8 u64
    //   + 16 u128 + 8 i64 (EMA) + 32 pubkey + 8 i64 (timelock)
    pub const LEN: usize = 8 + 32 * 3 + 8 * 3 + 1 + 1 + 8 + 8 + 16 + 8 + 32 + 8;
}

#[derive(Accounts)]
pub struct InitializeTreasury<'info> {
    /// Fee payer for Treasury rent. NOT necessarily the same as the
    /// `squads_multisig` argument (which becomes treasury.authority).
    /// Foundation may sponsor rent for community-deployed treasury instances.
    #[account(mut)]
    pub payer: Signer<'info>,
    /// Per-mint Treasury PDA (H-02 c530322 — bound to usdc_mint). LEN=162
    /// includes the C-04 1f995d7 window-accountant fields. Schema is v1
    /// (CURRENT_VERSION pattern from ping-token C-01 b4d606a would apply
    /// here in a future migration).
    #[account(init, payer = payer, space = Treasury::LEN, seeds = [b"treasury", usdc_mint.key().as_ref()], bump)]
    pub treasury: Account<'info, Treasury>,
    /// USDC mint — the principal currency this Treasury accountants.
    /// Foundation-controlled mainnet pubkey EPjFWdd5...
    pub usdc_mint: InterfaceAccount<'info, Mint>,
    // H-05 fix (per #22 c.4527297108): bind usdc_vault to (treasury PDA owner,
    // expected mint, no close authority). Same shape as earn-vault C-03
    // (2c35aee) + internal-swap C4 (564e6af).
    #[account(
        constraint = usdc_vault.owner == treasury.key() @ PommError::WrongVaultOwner,
        constraint = usdc_vault.mint == usdc_mint.key() @ PommError::WrongVaultMint,
        constraint = usdc_vault.close_authority.is_none() @ PommError::VaultMustNotBeCloseable,
    )]
    pub usdc_vault: InterfaceAccount<'info, TokenAccount>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct DepositUsdc<'info> {
    /// Depositor — any wallet can fund the POMM treasury. Signs the
    /// transfer. Foundation typically pre-funds; community can also top up.
    #[account(mut)]
    pub depositor: Signer<'info>,
    /// Per-mint Treasury PDA (H-02 c530322). mut for total_usdc increment.
    #[account(mut, seeds = [b"treasury", usdc_mint.key().as_ref()], bump = treasury.bump)]
    pub treasury: Account<'info, Treasury>,
    /// USDC mint — read-only, for transfer_checked decimals enforcement.
    #[account(address = treasury.usdc_mint @ PommError::WrongUsdcMint)]
    pub usdc_mint: InterfaceAccount<'info, Mint>,
    /// Depositor's USDC source.
    #[account(mut)]
    pub depositor_usdc_ata: InterfaceAccount<'info, TokenAccount>,
    /// Treasury's USDC reserve (owner == treasury PDA per H-05 2f10110).
    /// address-pinned to registered vault.
    #[account(mut, address = treasury.usdc_vault)]
    pub usdc_vault: InterfaceAccount<'info, TokenAccount>,
    pub token_program: Interface<'info, TokenInterface>,
}

impl<'info> DepositUsdc<'info> {
    fn transfer_ctx(&self) -> CpiContext<'_, '_, '_, 'info, TransferChecked<'info>> {
        CpiContext::new(self.token_program.to_account_info(), TransferChecked {
            from: self.depositor_usdc_ata.to_account_info(),
            mint: self.usdc_mint.to_account_info(),
            to: self.usdc_vault.to_account_info(),
            authority: self.depositor.to_account_info(),
        })
    }
}

#[derive(Accounts)]
pub struct MintLpPosition<'info> {
    /// Treasury authority — production: Squads multisig (H-02 #62 wraps).
    /// Currently enforced as a single-key signer via `address =`. Real
    /// CLMM CPI below uses Treasury PDA as the position owner, not
    /// authority (authority just authorizes the deploy decision).
    #[account(address = treasury.authority)]
    pub authority: Signer<'info>,
    /// Per-mint Treasury PDA — also the position owner for the Raydium
    /// CLMM personal position NFT. mut for C-04 accountant + C-02 EMA
    /// freshness + deployed_usdc bump.
    #[account(mut, seeds = [b"treasury", usdc_mint.key().as_ref()], bump = treasury.bump)]
    pub treasury: Account<'info, Treasury>,
    /// USDC mint — seed binding + reference for CLMM token_0 / token_1.
    #[account(address = treasury.usdc_mint @ PommError::WrongUsdcMint)]
    pub usdc_mint: InterfaceAccount<'info, Mint>,
    /// Treasury's USDC reserve — debited into the CLMM pool token vault.
    #[account(mut, address = treasury.usdc_vault)]
    pub usdc_vault: InterfaceAccount<'info, TokenAccount>,
    /// CHECK: Raydium CLMM program ID. Validated via
    /// `raydium_clmm::ID == raydium_clmm_program.key()` in the body.
    pub raydium_clmm_program: AccountInfo<'info>,
    /// CHECK: Raydium CLMM pool state account (USDC / $PING pool). Read
    /// via account_info.try_borrow_data() + the raydium-clmm pool layout
    /// once the CPI crate lands. Currently scaffolded as opaque AccountInfo
    /// so source ships before the crate is fetched.
    #[account(mut)]
    pub clmm_pool_state: AccountInfo<'info>,
    /// CHECK: Pool's token vault for token_0 (USDC). mut for the deposit.
    #[account(mut)]
    pub clmm_token_vault_0: AccountInfo<'info>,
    /// CHECK: Pool's token vault for token_1 ($PING). mut for the deposit.
    #[account(mut)]
    pub clmm_token_vault_1: AccountInfo<'info>,
    /// CHECK: Tick array lower bound for the position range. CLMM-internal.
    #[account(mut)]
    pub tick_array_lower: AccountInfo<'info>,
    /// CHECK: Tick array upper bound for the position range. CLMM-internal.
    #[account(mut)]
    pub tick_array_upper: AccountInfo<'info>,
    /// CHECK: Observation state (oracle ring buffer). mut because each
    /// CLMM swap updates the ring.
    #[account(mut)]
    pub clmm_observation_state: AccountInfo<'info>,
    /// CHECK: Personal position NFT account owned by treasury PDA. Created
    /// via raydium-clmm-cpi::cpi::open_position on first call (init_if_needed
    /// equivalent in the real crate); subsequent calls call
    /// increase_liquidity_v2 to add to the existing position.
    #[account(mut)]
    pub personal_position_state: AccountInfo<'info>,
    pub token_program: Interface<'info, TokenInterface>,
}

/// #62 C-01 Raydium CLMM CPI scaffold — autonomous source-side half per
/// shepherd coaching 2026-05-24. Constants + instruction-discriminator
/// dispatch defined here so the CPI shape lands in source before the
/// raydium-clmm-cpi crate is fetchable on bastion.
pub mod raydium_clmm {
    use anchor_lang::prelude::*;

    /// Raydium Concentrated Liquidity Market Maker program (mainnet).
    /// Pinned for build reproducibility under audit; the placeholder
    /// declare_id (per ADR 0018) means accidental deploy can't hit
    /// mainnet even with this CPI scaffold landed.
    pub fn id() -> Pubkey {
        // Mainnet CLMM program: CAMMCzo5YL8w4VFF8KVHrK22GGUsp5VTaW7grrKgrWqK
        Pubkey::try_from("CAMMCzo5YL8w4VFF8KVHrK22GGUsp5VTaW7grrKgrWqK")
            .expect("raydium-clmm program ID is a known-valid base58")
    }

    /// Instruction discriminator for increase_liquidity_v2 (per
    /// raydium-clmm IDL v0.1.x). Hand-derived as the first 8 bytes of
    /// sha256("global:increase_liquidity_v2"). Pinned here for the
    /// scaffold; the raydium-clmm-cpi crate exposes this as
    /// raydium_clmm_cpi::instruction::IncreaseLiquidityV2::DISCRIMINATOR
    /// when fetched.
    pub const INCREASE_LIQUIDITY_V2_DISCRIMINATOR: [u8; 8] = [
        0x86, 0xe3, 0x49, 0xc0, 0x47, 0x9d, 0x4c, 0xa1,
    ];

    /// Instruction discriminator for open_position_with_token22_nft
    /// (per raydium-clmm IDL v0.1.x). Used on first deploy when the
    /// personal_position_state PDA is uninitialized.
    pub const OPEN_POSITION_DISCRIMINATOR: [u8; 8] = [
        0x4d, 0x0e, 0xb1, 0xc9, 0x2c, 0xff, 0xc8, 0x77,
    ];
}

#[derive(Accounts)]
pub struct CollectFees<'info> {
    /// Treasury authority. NB: collect_fees itself is hard-disabled per
    /// H-01 600c647 — caller-supplied fees would be unverifiable without
    /// real CLMM fee-read CPI (rebuild scope).
    #[account(address = treasury.authority)]
    pub authority: Signer<'info>,
    /// Per-mint Treasury PDA — same revert-safety note as MintLpPosition.
    #[account(mut, seeds = [b"treasury", usdc_mint.key().as_ref()], bump = treasury.bump)]
    pub treasury: Account<'info, Treasury>,
    /// usdc_mint — seed binding (added in #22 CRIT #1 cleanup).
    #[account(address = treasury.usdc_mint @ PommError::WrongUsdcMint)]
    pub usdc_mint: InterfaceAccount<'info, Mint>,
}

#[derive(Accounts)]
pub struct AdminTreasury<'info> {
    /// Treasury authority — currently single-key dev path. Production:
    /// Squads multisig (H-02 architectural gate). Shared context for
    /// set_paused + propose/cancel_authority_rotation instructions.
    #[account(address = treasury.authority)]
    pub authority: Signer<'info>,
    /// Per-mint Treasury PDA. mut for is_paused + authority field updates.
    #[account(mut, seeds = [b"treasury", usdc_mint.key().as_ref()], bump = treasury.bump)]
    pub treasury: Account<'info, Treasury>,
    /// usdc_mint — seed binding for the per-mint Treasury PDA.
    #[account(address = treasury.usdc_mint @ PommError::WrongUsdcMint)]
    pub usdc_mint: InterfaceAccount<'info, Mint>,
}

#[derive(Accounts)]
pub struct FinalizeAuthorityRotation<'info> {
    /// Per-mint Treasury PDA. mut to flip authority + clear pending.
    #[account(mut, seeds = [b"treasury", usdc_mint.key().as_ref()], bump = treasury.bump)]
    pub treasury: Account<'info, Treasury>,
    #[account(address = treasury.usdc_mint @ PommError::WrongUsdcMint)]
    pub usdc_mint: InterfaceAccount<'info, Mint>,
    /// Anyone may finalize after timelock — new authority pulls ownership.
    pub caller: Signer<'info>,
}

#[derive(Accounts)]
pub struct UpdateEma<'info> {
    /// Per-mint Treasury PDA; mut for ema_price_x64 + ema_update_ts writes.
    #[account(mut, seeds = [b"treasury", usdc_mint.key().as_ref()], bump = treasury.bump)]
    pub treasury: Account<'info, Treasury>,
    /// USDC mint — seed binding.
    #[account(address = treasury.usdc_mint @ PommError::WrongUsdcMint)]
    pub usdc_mint: InterfaceAccount<'info, Mint>,
    /// Pyth price account for $PING/USDC. CHECK: validated inside update_ema
    /// via SolanaPriceAccount::account_info_to_feed.
    pub pyth_price_account: AccountInfo<'info>,
}

#[derive(Accounts)]
pub struct EmergencyWithdraw<'info> {
    /// Treasury authority (Squads multisig in prod). `address =` enforces
    /// signer matches the recorded authority; combined with the
    /// `is_paused` runtime check, this means only the multisig can
    /// drain — AND only after pausing first.
    #[account(address = treasury.authority)]
    pub authority: Signer<'info>,
    /// Per-mint Treasury PDA (H-02 c530322). mut for total_usdc decrement.
    #[account(mut, seeds = [b"treasury", usdc_mint.key().as_ref()], bump = treasury.bump)]
    pub treasury: Account<'info, Treasury>,
    /// USDC mint (read-only — decimals enforcement in transfer_checked).
    #[account(address = treasury.usdc_mint @ PommError::WrongUsdcMint)]
    pub usdc_mint: InterfaceAccount<'info, Mint>,
    /// Treasury's USDC reserve. address-pinned to the registered vault.
    #[account(mut, address = treasury.usdc_vault)]
    pub usdc_vault: InterfaceAccount<'info, TokenAccount>,
    /// H-04 fix (per #22 c.4527297108): emergency_withdraw destination
    /// MUST be owned by treasury.authority (Squads multisig in prod), not
    /// any caller-chosen wallet. Without this, a single-signer pause-and-
    /// drain attack works: pause treasury → emergency_withdraw to attacker
    /// ATA → unpause. ADR 0009 says "Multisig can only pause" — this
    /// constraint enforces that even an emergency exit can only route
    /// funds back to the authority's control.
    #[account(
        mut,
        constraint = destination_ata.owner == treasury.authority @ PommError::WrongEmergencyDestination,
        constraint = destination_ata.mint == usdc_mint.key() @ PommError::WrongVaultMint,
    )]
    pub destination_ata: InterfaceAccount<'info, TokenAccount>,
    pub token_program: Interface<'info, TokenInterface>,
}

impl<'info> EmergencyWithdraw<'info> {
    fn transfer_ctx(&self) -> CpiContext<'_, '_, '_, 'info, TransferChecked<'info>> {
        CpiContext::new(self.token_program.to_account_info(), TransferChecked {
            from: self.usdc_vault.to_account_info(),
            mint: self.usdc_mint.to_account_info(),
            to: self.destination_ata.to_account_info(),
            authority: self.treasury.to_account_info(),
        })
    }
}

#[event]
#[derive(Debug)]
pub struct DepositEvent {
    pub treasury: Pubkey,
    pub depositor: Pubkey,
    pub amount: u64,
}

#[event]
#[derive(Debug)]
pub struct LpMintEvent {
    pub treasury: Pubkey,
    pub amount: u64,
    pub oracle_price_x64: u128,
}

#[event]
#[derive(Debug)]
pub struct FeesCollected {
    pub treasury: Pubkey,
    pub amount: u64,
}

#[event]
#[derive(Debug)]
pub struct PausedEvent {
    pub treasury: Pubkey,
    pub paused: bool,
    /// H-06 fix (#62): which authority key triggered the pause toggle.
    /// Mirror of internal-swap PausedEvent.caller — auditor + incident
    /// response indexer needs both who + when.
    pub caller: Pubkey,
    pub ts: i64,
}

#[event]
#[derive(Debug)]
pub struct EmergencyWithdrawEvent {
    pub treasury: Pubkey,
    pub amount: u64,
}

#[event]
#[derive(Debug)]
pub struct AuthorityRotated {
    pub treasury: Pubkey,
    pub old_authority: Pubkey,
    pub new_authority: Pubkey,
}

#[event]
#[derive(Debug)]
pub struct AuthorityRotationProposed {
    pub treasury: Pubkey,
    pub current_authority: Pubkey,
    pub proposed_authority: Pubkey,
    pub unlock_ts: i64,
    pub ts: i64,
}

#[event]
#[derive(Debug)]
pub struct AuthorityRotationCancelled {
    pub treasury: Pubkey,
    pub cancelled_authority: Pubkey,
    pub ts: i64,
}

#[event]
#[derive(Debug)]
pub struct TreasuryInitialized {
    pub treasury: Pubkey,
    pub authority: Pubkey,
    pub usdc_mint: Pubkey,
    pub usdc_vault: Pubkey,
    pub window_start_ts: i64,
    pub bump: u8,
}

#[event]
#[derive(Debug)]
pub struct EmaUpdated {
    pub treasury: Pubkey,
    pub pyth_price_x64: u128,
    pub ema_price_x64: u128,
    pub update_ts: i64,
}

#[error_code]
pub enum PommError {
    #[msg("Treasury is paused")]
    Paused,
    #[msg("Amount must be > 0")]
    ZeroAmount,
    #[msg("Oracle price outside EMA band")]
    PriceOutOfBand,
    #[msg("Per-day deployment cap exceeded")]
    DailyCapExceeded,
    #[msg("Emergency withdraw requires paused state")]
    EmergencyRequiresPause,
    #[msg("Arithmetic overflow")]
    MathOverflow,
    #[msg("usdc_vault.owner must equal the treasury PDA")]
    WrongVaultOwner,
    #[msg("usdc_vault.mint must equal the usdc_mint passed to initialize_treasury")]
    WrongVaultMint,
    #[msg("usdc_vault.close_authority must be None (vault must not be closeable)")]
    VaultMustNotBeCloseable,
    #[msg("emergency_withdraw destination must be owned by treasury.authority (multisig)")]
    WrongEmergencyDestination,
    #[msg("New authority cannot be the zero pubkey")]
    ZeroPubkey,
    #[msg("collect_fees disabled in scaffold; full rebuild per ADR 0009 (real CLMM fee-read CPI) required first")]
    CollectFeesDisabledUntilRebuild,
    #[msg("mint_lp_position disabled in scaffold; full rebuild per ADR 0009 (Pyth oracle + on-chain EMA + Raydium CLMM CPI) required first")]
    DeployToClmmDisabledUntilRebuild,
    #[msg("Pyth price account could not be parsed as a SolanaPriceAccount")]
    OracleAccountInvalid,
    #[msg("Pyth price is stale (>MAX_PYTH_STALENESS_SEC since last update) or non-positive")]
    OracleStaleOrInvalid,
    #[msg("Pyth confidence interval exceeds MAX_PYTH_CONF_BPS — publishers disagree too widely")]
    OracleConfidenceTooWide,
    #[msg("Proposed authority must differ from current authority")]
    SameAuthority,
    #[msg("No pending authority rotation to finalize/cancel")]
    NoPendingRotation,
    #[msg("Authority rotation timelock (7 days) has not elapsed yet")]
    TimelockNotElapsed,
    #[msg("EMA accumulator has never been updated — call update_ema first")]
    EmaUnseeded,
    #[msg("EMA is stale (>MAX_EMA_STALENESS_SEC since last update) — call update_ema first")]
    EmaStale,
    #[msg("raydium_clmm_program account does not match the pinned mainnet CLMM program ID")]
    WrongRaydiumCllmProgram,
    #[msg("Claimed authority is not the expected Squads multisig vault PDA (H-02)")]
    WrongAuthority,
    #[msg("usdc_mint must equal treasury.usdc_mint — defense-in-depth on top of PDA seed binding (#22 CRIT #1)")]
    WrongUsdcMint,
}
