use anchor_lang::prelude::*;
use anchor_spl::token_interface::{
    self, Mint, TokenAccount, TokenInterface, TransferChecked,
};
use pyth_sdk_solana::state::SolanaPriceAccount;

// ============================================================================
// ⚠️  DO NOT DEPLOY THIS PROGRAM TO MAINNET — per ADR 0018 + #22 EPIC gates.
// ============================================================================
// Pre-audit review 2026-05-24 (#22 c.4527278904) surfaced 23 findings on this
// scaffold:
//   - 5 Critical: missing DO-NOT-DEPLOY guard (closed by this banner); literal
//     placeholder declare_id won't decode as a pubkey; operator-drain via
//     pool.usdc_balance/pool.ping_balance counters never reconciled with real
//     vault balances; initialize_pool doesn't constrain vault mint/owner/
//     close_authority; seeds = [b"pool"] front-runnable single global PDA
//   - 6 High: no rotate_authority (migrate-to-multisig path); no multisig on
//     authority field (ADR 0017); no minimum_amount_out slippage param;
//     missing Pyth/Switchboard oracle integration despite ADR 0009 mandate;
//     no oracle accounts in swap contexts; unaccountable pause
//
// Largest design-vs-impl gap: ADR 0009 mandates Pyth-priced swaps × (1 ± 0.3%
// spread); code implements naive x*y=k constant-product. Reconciliation
// required.
//
// Mainnet deploy gated on (per #22 EPIC):
//   1. ADR 0009 full implementation (Pyth oracle + Raydium CLMM CPI on the
//      pomm side, slippage protection, multisig governance + 7d timelock)
//   2. OtterSec audit + critical/high findings remediated
//   3. Cayman Foundation incorporation
//   4. Real program keypair generated by Squads multisig
// L-01 ADR 0018 compile_error guard (mirrors ping-token 2bd1c24).
#[cfg(all(feature = "mainnet-ready", not(feature = "audit-passed")))]
compile_error!(
    "internal-swap: mainnet-ready feature requires audit-passed feature \
     (set only AFTER OtterSec audit completes per #22 EPIC + ADR 0018)"
);
declare_id!("InternalSwapProgr4mPubKeyP1ace0001111111111");

const MAX_SPREAD_BPS: u16 = 100;
const HEDGE_THRESHOLD_BPS: u16 = 2_000;

#[program]
pub mod internal_swap {
    use super::*;

    pub fn initialize_pool(ctx: Context<InitializePool>, spread_bps: u16) -> Result<()> {
        require!(spread_bps <= MAX_SPREAD_BPS, SwapError::SpreadTooHigh);
        let pool = &mut ctx.accounts.pool;
        pool.authority = ctx.accounts.authority.key();
        pool.usdc_mint = ctx.accounts.usdc_mint.key();
        pool.ping_mint = ctx.accounts.ping_mint.key();
        pool.usdc_vault = ctx.accounts.usdc_vault.key();
        pool.ping_vault = ctx.accounts.ping_vault.key();
        pool.spread_bps = spread_bps;
        pool.usdc_balance = 0;
        pool.ping_balance = 0;
        pool.is_paused = false;
        pool.bump = ctx.bumps.pool;

        // M-04 fix (#22 c.4527278904): dashboards/indexers need a creation
        // event to know when a pool exists + its config. Without this, the
        // only way to detect a new pool is to crawl every program account
        // by type, which is operationally expensive for indexers.
        emit!(PoolInitialized {
            pool: pool.key(),
            authority: pool.authority,
            usdc_mint: pool.usdc_mint,
            ping_mint: pool.ping_mint,
            usdc_vault: pool.usdc_vault,
            ping_vault: pool.ping_vault,
            spread_bps: pool.spread_bps,
            bump: pool.bump,
        });
        Ok(())
    }

    pub fn swap_usdc_for_ping(
        ctx: Context<SwapUsdcForPing>,
        amount_in: u64,
        minimum_amount_out: u64,
    ) -> Result<()> {
        require!(!ctx.accounts.pool.is_paused, SwapError::Paused);
        require!(amount_in > 0, SwapError::ZeroAmount);

        // C3 fix (per #22 c.4527278904): read REAL vault balances from the
        // SPL token accounts, not the trusted pool.{usdc,ping}_balance
        // counters. Original code let any out-of-band vault movement
        // de-sync pricing and enable arbitrage drain. By reading
        // *_vault.amount directly, the price is always derived from
        // ground truth.
        let pool = &ctx.accounts.pool;
        let real_usdc = ctx.accounts.usdc_vault.amount;
        let real_ping = ctx.accounts.ping_vault.amount;
        require!(real_ping > 0, SwapError::InsufficientLiquidity);

        let amount_out = quote_usdc_to_ping(
            amount_in,
            real_usdc,
            real_ping,
            pool.spread_bps,
        )?;
        require!(amount_out > 0, SwapError::OutputTooSmall);
        require!(amount_out <= real_ping, SwapError::InsufficientLiquidity);
        // H-03 fix (per #22 c.4527278904): standard DEX slippage protection.
        // Client computes expected_output off-chain, applies their tolerance
        // (typically 0.5-1.0%), passes the floor. If on-chain quote is worse
        // (sandwich attack, stale price, etc), revert. Without this, MEV bots
        // can profitably sandwich every user trade.
        require!(amount_out >= minimum_amount_out, SwapError::SlippageExceeded);

        // H-04 fix (#62 c.4527806799): cross-check AMM-derived price against
        // Pyth oracle. AMM implied price = amount_in / amount_out (USDC per
        // PING). Scale to Q64.64 to match read_pyth_ping_per_usdc_x64's
        // output format, then assert within MAX_ORACLE_DEVIATION_BPS (3%).
        let amm_usdc_per_ping_x64 = (amount_in as u128)
            .checked_shl(64)
            .ok_or(SwapError::MathOverflow)?
            .checked_div(amount_out as u128)
            .ok_or(SwapError::MathOverflow)?;
        let oracle_usdc_per_ping_x64 = read_pyth_ping_per_usdc_x64(
            &ctx.accounts.pyth_price_account,
            &Clock::get()?,
        )?;
        assert_amm_within_oracle_band(amm_usdc_per_ping_x64, oracle_usdc_per_ping_x64)?;

        token_interface::transfer_checked(
            ctx.accounts.transfer_in_ctx(),
            amount_in,
            ctx.accounts.usdc_mint.decimals,
        )?;

        // C5 fix (per #22 c.4527278904): signer seeds bind to pool's
        // (usdc_mint, ping_mint) pair. Same per-asset PDA pattern as
        // earn-vault C-04 (f7ea54f) + ping-token H-01 (2deaace).
        let usdc_mint_key = ctx.accounts.pool.usdc_mint;
        let ping_mint_key = ctx.accounts.pool.ping_mint;
        let seeds = &[
            b"pool".as_ref(),
            usdc_mint_key.as_ref(),
            ping_mint_key.as_ref(),
            &[ctx.accounts.pool.bump],
        ];
        let signer = &[&seeds[..]];
        token_interface::transfer_checked(
            ctx.accounts.transfer_out_ctx().with_signer(signer),
            amount_out,
            ctx.accounts.ping_mint.decimals,
        )?;

        let pool = &mut ctx.accounts.pool;
        pool.usdc_balance = pool.usdc_balance.checked_add(amount_in).ok_or(SwapError::MathOverflow)?;
        pool.ping_balance = pool.ping_balance.checked_sub(amount_out).ok_or(SwapError::MathOverflow)?;

        emit!(SwapEvent {
            pool: pool.key(),
            user: ctx.accounts.user.key(),
            direction: SwapDirection::UsdcForPing,
            amount_in,
            amount_out,
        });
        Ok(())
    }

    pub fn swap_ping_for_usdc(
        ctx: Context<SwapPingForUsdc>,
        amount_in: u64,
        minimum_amount_out: u64,
    ) -> Result<()> {
        require!(!ctx.accounts.pool.is_paused, SwapError::Paused);
        require!(amount_in > 0, SwapError::ZeroAmount);

        // C3 fix: read REAL vault balances (see swap_usdc_for_ping above).
        let pool = &ctx.accounts.pool;
        let real_usdc = ctx.accounts.usdc_vault.amount;
        let real_ping = ctx.accounts.ping_vault.amount;
        require!(real_usdc > 0, SwapError::InsufficientLiquidity);

        let amount_out = quote_ping_to_usdc(
            amount_in,
            real_ping,
            real_usdc,
            pool.spread_bps,
        )?;
        require!(amount_out > 0, SwapError::OutputTooSmall);
        require!(amount_out <= real_usdc, SwapError::InsufficientLiquidity);
        // H-03 slippage protection — see swap_usdc_for_ping above.
        require!(amount_out >= minimum_amount_out, SwapError::SlippageExceeded);

        // H-04 Pyth band-check (mirror of swap_usdc_for_ping). Note: this
        // direction's AMM-implied USDC-per-PING is amount_out / amount_in
        // (inverse of the other side because we're paying PING here).
        let amm_usdc_per_ping_x64 = (amount_out as u128)
            .checked_shl(64)
            .ok_or(SwapError::MathOverflow)?
            .checked_div(amount_in as u128)
            .ok_or(SwapError::MathOverflow)?;
        let oracle_usdc_per_ping_x64 = read_pyth_ping_per_usdc_x64(
            &ctx.accounts.pyth_price_account,
            &Clock::get()?,
        )?;
        assert_amm_within_oracle_band(amm_usdc_per_ping_x64, oracle_usdc_per_ping_x64)?;

        token_interface::transfer_checked(
            ctx.accounts.transfer_in_ctx(),
            amount_in,
            ctx.accounts.ping_mint.decimals,
        )?;

        // C5 fix (per #22 c.4527278904): signer seeds bind to pool's
        // (usdc_mint, ping_mint) pair. Same per-asset PDA pattern as
        // earn-vault C-04 (f7ea54f) + ping-token H-01 (2deaace).
        let usdc_mint_key = ctx.accounts.pool.usdc_mint;
        let ping_mint_key = ctx.accounts.pool.ping_mint;
        let seeds = &[
            b"pool".as_ref(),
            usdc_mint_key.as_ref(),
            ping_mint_key.as_ref(),
            &[ctx.accounts.pool.bump],
        ];
        let signer = &[&seeds[..]];
        token_interface::transfer_checked(
            ctx.accounts.transfer_out_ctx().with_signer(signer),
            amount_out,
            ctx.accounts.usdc_mint.decimals,
        )?;

        let pool = &mut ctx.accounts.pool;
        pool.ping_balance = pool.ping_balance.checked_add(amount_in).ok_or(SwapError::MathOverflow)?;
        pool.usdc_balance = pool.usdc_balance.checked_sub(amount_out).ok_or(SwapError::MathOverflow)?;

        emit!(SwapEvent {
            pool: pool.key(),
            user: ctx.accounts.user.key(),
            direction: SwapDirection::PingForUsdc,
            amount_in,
            amount_out,
        });
        Ok(())
    }

    pub fn set_spread_bps(ctx: Context<AdminPool>, spread_bps: u16) -> Result<()> {
        require!(spread_bps <= MAX_SPREAD_BPS, SwapError::SpreadTooHigh);
        ctx.accounts.pool.spread_bps = spread_bps;
        emit!(SpreadChanged { pool: ctx.accounts.pool.key(), spread_bps });
        Ok(())
    }

    pub fn set_paused(ctx: Context<AdminPool>, paused: bool) -> Result<()> {
        ctx.accounts.pool.is_paused = paused;
        // H-06 fix (#62 c.4527806799): emit caller + timestamp for on-chain
        // accountability. Pre-fix PausedEvent omitted them, so an unpause
        // couldn't be traced to a specific authority key + when. Auditor +
        // incident-response indexer needs both.
        emit!(PausedEvent {
            pool: ctx.accounts.pool.key(),
            paused,
            caller: ctx.accounts.authority.key(),
            ts: Clock::get()?.unix_timestamp,
        });
        Ok(())
    }

    /// Rotate the pool authority to a new pubkey. H-01 fix (#22 c.4527278904).
    /// Mirror of earn-vault rotate_authority (2d89968) + ping-token H-03
    /// (f1cfab4). Needed to migrate from single-key dev authority to a Squads
    /// multisig (ADR 0019) without redeploying — placeholder declare_id
    /// forbids redeploy.
    pub fn rotate_authority(
        ctx: Context<AdminPool>,
        new_authority: Pubkey,
    ) -> Result<()> {
        require!(new_authority != Pubkey::default(), SwapError::ZeroPubkey);
        let old_authority = ctx.accounts.pool.authority;
        ctx.accounts.pool.authority = new_authority;
        emit!(AuthorityRotated {
            pool: ctx.accounts.pool.key(),
            old_authority,
            new_authority,
        });
        Ok(())
    }
}

fn quote_usdc_to_ping(
    amount_in_usdc: u64,
    pool_usdc: u64,
    pool_ping: u64,
    spread_bps: u16,
) -> Result<u64> {
    let _ = pool_usdc;
    let gross = (amount_in_usdc as u128)
        .checked_mul(pool_ping as u128)
        .ok_or(SwapError::MathOverflow)?
        .checked_div((amount_in_usdc as u128).checked_add(pool_usdc as u128).ok_or(SwapError::MathOverflow)?)
        .ok_or(SwapError::MathOverflow)?;
    apply_spread(gross, spread_bps)
}

/// #62 H-04 rebuild start (ADR 0009 Pyth integration). Cross-checks the
/// AMM-derived price against a Pyth oracle reference and reverts if the
/// deviation exceeds MAX_ORACLE_DEVIATION_BPS. Caller wires in the Pyth
/// price account; on devnet this can be a Pyth mock (pyth-sdk-solana ships
/// fixture helpers). Production reads the canonical SOL/$PING/USDC feeds.
///
/// MAX_ORACLE_DEVIATION_BPS = 300 (3%) is intentionally wide for an AMM
/// pool that may also serve $PING-specific liquidity discontinuities.
/// Tighten to 100 (1%) post-launch once Raydium CLMM CPI lands and the
/// AMM curve more reliably tracks oracle.
///
/// Returns the AMM quote unchanged if oracle band check passes; reverts
/// with PriceDeviatesFromOracle otherwise. Pure validation — does not
/// override the AMM quote.

pub const MAX_ORACLE_DEVIATION_BPS: u16 = 300;


fn assert_amm_within_oracle_band(
    amm_usdc_per_ping_x64: u128,
    oracle_usdc_per_ping_x64: u128,
) -> Result<()> {
    // Compute |amm - oracle| / oracle in bps. Saturating math — at scaffold
    // start we accept clamping to u128::MAX rather than overflow-revert; the
    // band check below catches that case (any saturated diff > band → revert).
    let diff = if amm_usdc_per_ping_x64 > oracle_usdc_per_ping_x64 {
        amm_usdc_per_ping_x64 - oracle_usdc_per_ping_x64
    } else {
        oracle_usdc_per_ping_x64 - amm_usdc_per_ping_x64
    };
    let band = oracle_usdc_per_ping_x64
        .saturating_mul(MAX_ORACLE_DEVIATION_BPS as u128)
        .saturating_div(10_000);
    require!(diff <= band, SwapError::PriceDeviatesFromOracle);
    Ok(())
}

/// #62 H-04 helper: read $PING-per-USDC price from a Pyth price account
/// + staleness-check + confidence-interval-check + format as Q64.64 fixed
/// point matching assert_amm_within_oracle_band's expected scale.
///
/// On devnet/local this can be a Pyth mock fixture; production uses the
/// canonical $PING/USDC feed (TBD post-TGE — Pyth lists post-Raydium
/// liquidity onboarding).
///
/// Staleness threshold MAX_PYTH_STALENESS_SEC = 60 — if last price update
/// is older than 60s the swap reverts. Pyth typically updates every ~400ms
/// on mainnet so this is a generous tolerance.

pub const MAX_PYTH_STALENESS_SEC: i64 = 60;


fn read_pyth_ping_per_usdc_x64(
    price_account: &AccountInfo,
    clock: &Clock,
) -> Result<u128> {
    let price_feed = SolanaPriceAccount::account_info_to_feed(price_account)
        .map_err(|_| error!(SwapError::OracleAccountInvalid))?;
    let price = price_feed
        .get_price_no_older_than(clock.unix_timestamp, MAX_PYTH_STALENESS_SEC as u64)
        .ok_or(error!(SwapError::OracleStaleOrInvalid))?;
    // Reject if price is non-positive (Pyth permits negative for derivatives;
    // for a spot price feed we treat this as bad data).
    require!(price.price > 0, SwapError::OracleStaleOrInvalid);
    // Convert Pyth's i64 + expo into a Q64.64 fixed-point matching
    // assert_amm_within_oracle_band's amm_x64 scale. Pyth.expo is typically
    // negative (e.g., -8 means price is in units of 10^-8 USD per unit).
    let mantissa = price.price as u128;
    let q64_64_one: u128 = 1u128 << 64;
    // value_x64 = mantissa * 2^64 / 10^|expo|
    let abs_expo = price.expo.unsigned_abs() as u32;
    let scale = 10u128
        .checked_pow(abs_expo)
        .ok_or(SwapError::MathOverflow)?;
    mantissa
        .checked_mul(q64_64_one)
        .ok_or(SwapError::MathOverflow)?
        .checked_div(scale)
        .ok_or(SwapError::MathOverflow.into())
}

fn quote_ping_to_usdc(
    amount_in_ping: u64,
    pool_ping: u64,
    pool_usdc: u64,
    spread_bps: u16,
) -> Result<u64> {
    let _ = pool_ping;
    let gross = (amount_in_ping as u128)
        .checked_mul(pool_usdc as u128)
        .ok_or(SwapError::MathOverflow)?
        .checked_div((amount_in_ping as u128).checked_add(pool_ping as u128).ok_or(SwapError::MathOverflow)?)
        .ok_or(SwapError::MathOverflow)?;
    apply_spread(gross, spread_bps)
}

fn apply_spread(gross: u128, spread_bps: u16) -> Result<u64> {
    let net = gross
        .checked_mul((10_000 - spread_bps) as u128)
        .ok_or(SwapError::MathOverflow)?
        .checked_div(10_000)
        .ok_or(SwapError::MathOverflow)?;
    if net > u64::MAX as u128 { return err!(SwapError::MathOverflow); }
    Ok(net as u64)
}

/// #62 H-02 Squads V4 multisig CPI scaffold — autonomous source-side half
/// per shepherd coaching 2026-05-24. Constants + helper for verifying the
/// signer is the vault-PDA of a Squads multisig (not just any single key).
/// SDK fetch + real CPI calls land on a build host with cargo; the pattern
/// + program ID + PDA derivation are source-shippable now.
pub mod squads_multisig {
    use anchor_lang::prelude::*;

    /// Squads Protocol V4 program (mainnet). Pinned for build
    /// reproducibility under audit.
    pub fn id() -> Pubkey {
        // Mainnet Squads V4: SQDS4ep65T869zMMBKyuUq6aD6EgTu8psMjkvj52pCf
        Pubkey::try_from("SQDS4ep65T869zMMBKyuUq6aD6EgTu8psMjkvj52pCf")
            .expect("Squads V4 program ID is a known-valid base58")
    }

    /// Derive the canonical Squads V4 vault PDA for (multisig_pda,
    /// vault_index). Multisigs have N vaults — the protocol convention
    /// is vault_index = 0 for the primary treasury vault.
    ///
    /// PDA seeds: [b"multisig", multisig_pda.as_ref(), b"vault", &[vault_index]]
    ///
    /// Use this to assert a signer is in fact a multisig vault PDA (not
    /// a single dev key) before allowing privileged operations.
    pub fn vault_pda(multisig_pda: &Pubkey, vault_index: u8) -> (Pubkey, u8) {
        Pubkey::find_program_address(
            &[
                b"multisig",
                multisig_pda.as_ref(),
                b"vault",
                &[vault_index],
            ],
            &id(),
        )
    }

    /// Assert that `claimed_authority` is the Squads vault PDA derived
    /// from `multisig_pda` at `vault_index`. Returns Err(WrongAuthority)
    /// if not. Belt-and-braces alongside Anchor's Signer<'info> +
    /// `address = ...` constraints.
    ///
    /// Note: this does NOT verify the multisig itself has executed the
    /// underlying intent — that's enforced by the Squads program when
    /// the vault PDA signs (only Squads can sign as that PDA via CPI
    /// from a Squads transaction execution). The check here ensures
    /// the *pubkey shape* matches a multisig vault, blocking
    /// accidental single-key deploys.
    pub fn assert_is_vault_pda(
        claimed_authority: &Pubkey,
        multisig_pda: &Pubkey,
        vault_index: u8,
    ) -> Result<()> {
        let (expected, _bump) = vault_pda(multisig_pda, vault_index);
        require_keys_eq!(*claimed_authority, expected, crate::SwapError::WrongAuthority);
        Ok(())
    }
}

pub fn needs_hedge(pool_usdc: u64, pool_ping_usdc_value: u64) -> bool {
    if pool_usdc == 0 || pool_ping_usdc_value == 0 { return false; }
    let larger = pool_usdc.max(pool_ping_usdc_value) as u128;
    let smaller = pool_usdc.min(pool_ping_usdc_value) as u128;
    let drift_bps = (larger.checked_sub(smaller).unwrap_or(0))
        .checked_mul(10_000)
        .and_then(|x| x.checked_div(larger))
        .unwrap_or(0) as u16;
    drift_bps > HEDGE_THRESHOLD_BPS
}

#[account]
#[derive(Debug)]
pub struct Pool {
    pub authority: Pubkey,
    pub usdc_mint: Pubkey,
    pub ping_mint: Pubkey,
    pub usdc_vault: Pubkey,
    pub ping_vault: Pubkey,
    pub usdc_balance: u64,
    pub ping_balance: u64,
    pub spread_bps: u16,
    pub is_paused: bool,
    pub bump: u8,
}

impl Pool {
    pub const LEN: usize = 8 + 32 * 5 + 8 * 2 + 2 + 1 + 1;
}

#[derive(Accounts)]
pub struct InitializePool<'info> {
    #[account(mut)]
    pub authority: Signer<'info>,
    #[account(init, payer = authority, space = Pool::LEN, seeds = [b"pool", usdc_mint.key().as_ref(), ping_mint.key().as_ref()], bump)]
    pub pool: Account<'info, Pool>,
    pub usdc_mint: InterfaceAccount<'info, Mint>,
    pub ping_mint: InterfaceAccount<'info, Mint>,
    // C4 fix (per #22 c.4527278904): bind vaults to (pool PDA, expected mint,
    // no close authority). Same shape as earn-vault C-03 (2c35aee).
    #[account(
        constraint = usdc_vault.owner == pool.key() @ SwapError::WrongVaultOwner,
        constraint = usdc_vault.mint == usdc_mint.key() @ SwapError::WrongVaultMint,
        constraint = usdc_vault.close_authority.is_none() @ SwapError::VaultMustNotBeCloseable,
    )]
    pub usdc_vault: InterfaceAccount<'info, TokenAccount>,
    #[account(
        constraint = ping_vault.owner == pool.key() @ SwapError::WrongVaultOwner,
        constraint = ping_vault.mint == ping_mint.key() @ SwapError::WrongVaultMint,
        constraint = ping_vault.close_authority.is_none() @ SwapError::VaultMustNotBeCloseable,
    )]
    pub ping_vault: InterfaceAccount<'info, TokenAccount>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct SwapUsdcForPing<'info> {
    /// Swapper — pays USDC, receives $PING. Signs the transfer.
    #[account(mut)]
    pub user: Signer<'info>,
    /// Per-(usdc,ping)-mint Pool PDA (C5 d238aa7). mut because pool.usdc_balance
    /// / pool.ping_balance breadcrumb counters update post-swap (the actual
    /// quote derives from real vault balances per C3 8e77f7c).
    #[account(mut, seeds = [b"pool", pool.usdc_mint.as_ref(), pool.ping_mint.as_ref()], bump = pool.bump)]
    pub pool: Account<'info, Pool>,
    /// USDC mint — read-only, for transfer_checked decimals enforcement.
    pub usdc_mint: InterfaceAccount<'info, Mint>,
    /// $PING mint — read-only, for transfer_checked decimals enforcement.
    pub ping_mint: InterfaceAccount<'info, Mint>,
    /// User's USDC source.
    #[account(mut)]
    pub user_usdc_ata: InterfaceAccount<'info, TokenAccount>,
    /// User's $PING destination.
    #[account(mut)]
    pub user_ping_ata: InterfaceAccount<'info, TokenAccount>,
    /// Pool's USDC reserve (owner == pool PDA per C4 564e6af). `address =`
    /// pins to the registered vault; quote reads from .amount per C3 8e77f7c.
    #[account(mut, address = pool.usdc_vault)]
    pub usdc_vault: InterfaceAccount<'info, TokenAccount>,
    /// Pool's $PING reserve. Source of swap output.
    #[account(mut, address = pool.ping_vault)]
    pub ping_vault: InterfaceAccount<'info, TokenAccount>,
    /// H-04 fix (#62 c.4527806799): Pyth price account for $PING/USDC.
    /// Read via read_pyth_ping_per_usdc_x64 + checked against AMM-derived
    /// price via assert_amm_within_oracle_band (MAX_ORACLE_DEVIATION_BPS=300).
    /// CHECK: validated inside the helper via SolanaPriceAccount::account_info_to_feed
    /// (which verifies owner == pyth-oracle program + magic bytes).
    /// Note: read-only AccountInfo (no #[account] constraints) so devnet
    /// can swap in a Pyth mock fixture.
    /// CHECK: see read_pyth_ping_per_usdc_x64 implementation
    pub pyth_price_account: AccountInfo<'info>,
    pub token_program: Interface<'info, TokenInterface>,
}

impl<'info> SwapUsdcForPing<'info> {
    fn transfer_in_ctx(&self) -> CpiContext<'_, '_, '_, 'info, TransferChecked<'info>> {
        CpiContext::new(self.token_program.to_account_info(), TransferChecked {
            from: self.user_usdc_ata.to_account_info(),
            mint: self.usdc_mint.to_account_info(),
            to: self.usdc_vault.to_account_info(),
            authority: self.user.to_account_info(),
        })
    }
    fn transfer_out_ctx(&self) -> CpiContext<'_, '_, '_, 'info, TransferChecked<'info>> {
        CpiContext::new(self.token_program.to_account_info(), TransferChecked {
            from: self.ping_vault.to_account_info(),
            mint: self.ping_mint.to_account_info(),
            to: self.user_ping_ata.to_account_info(),
            authority: self.pool.to_account_info(),
        })
    }
}

#[derive(Accounts)]
pub struct SwapPingForUsdc<'info> {
    /// Swapper — pays $PING, receives USDC. Signs the transfer.
    #[account(mut)]
    pub user: Signer<'info>,
    /// Per-(usdc,ping)-mint Pool PDA (C5 d238aa7). mut for breadcrumb counter
    /// updates; quote derives from real vault balances per C3 8e77f7c.
    #[account(mut, seeds = [b"pool", pool.usdc_mint.as_ref(), pool.ping_mint.as_ref()], bump = pool.bump)]
    pub pool: Account<'info, Pool>,
    /// USDC mint — read-only, for transfer_checked decimals enforcement.
    pub usdc_mint: InterfaceAccount<'info, Mint>,
    /// $PING mint — read-only, for transfer_checked decimals enforcement.
    pub ping_mint: InterfaceAccount<'info, Mint>,
    /// User's $PING source (debited).
    #[account(mut)]
    pub user_ping_ata: InterfaceAccount<'info, TokenAccount>,
    /// User's USDC destination (credited).
    #[account(mut)]
    pub user_usdc_ata: InterfaceAccount<'info, TokenAccount>,
    /// Pool's $PING reserve (owner == pool PDA per C4 564e6af). address-pinned.
    #[account(mut, address = pool.ping_vault)]
    pub ping_vault: InterfaceAccount<'info, TokenAccount>,
    /// Pool's USDC reserve (source of swap output).
    #[account(mut, address = pool.usdc_vault)]
    pub usdc_vault: InterfaceAccount<'info, TokenAccount>,
    /// H-04 Pyth price account — same shape as SwapUsdcForPing.
    /// CHECK: validated inside read_pyth_ping_per_usdc_x64 helper.
    pub pyth_price_account: AccountInfo<'info>,
    pub token_program: Interface<'info, TokenInterface>,
}

impl<'info> SwapPingForUsdc<'info> {
    fn transfer_in_ctx(&self) -> CpiContext<'_, '_, '_, 'info, TransferChecked<'info>> {
        CpiContext::new(self.token_program.to_account_info(), TransferChecked {
            from: self.user_ping_ata.to_account_info(),
            mint: self.ping_mint.to_account_info(),
            to: self.ping_vault.to_account_info(),
            authority: self.user.to_account_info(),
        })
    }
    fn transfer_out_ctx(&self) -> CpiContext<'_, '_, '_, 'info, TransferChecked<'info>> {
        CpiContext::new(self.token_program.to_account_info(), TransferChecked {
            from: self.usdc_vault.to_account_info(),
            mint: self.usdc_mint.to_account_info(),
            to: self.user_usdc_ata.to_account_info(),
            authority: self.pool.to_account_info(),
        })
    }
}

#[derive(Accounts)]
pub struct AdminPool<'info> {
    /// Pool authority — currently single-key dev authority. Production
    /// path is Squads multisig (H-02 architectural gate). `address =`
    /// enforces signer matches recorded authority. Shared context for
    /// set_paused + rotate_authority instructions.
    #[account(address = pool.authority)]
    pub authority: Signer<'info>,
    /// Per-(usdc,ping)-mint Pool PDA (C5 d238aa7). mut for is_paused +
    /// authority field updates from set_paused / rotate_authority.
    #[account(mut, seeds = [b"pool", pool.usdc_mint.as_ref(), pool.ping_mint.as_ref()], bump = pool.bump)]
    pub pool: Account<'info, Pool>,
}

#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub enum SwapDirection {
    UsdcForPing,
    PingForUsdc,
}

#[event]
#[derive(Debug)]
pub struct SwapEvent {
    pub pool: Pubkey,
    pub user: Pubkey,
    pub direction: SwapDirection,
    pub amount_in: u64,
    pub amount_out: u64,
}

#[event]
#[derive(Debug)]
pub struct SpreadChanged {
    pub pool: Pubkey,
    pub spread_bps: u16,
}

#[event]
#[derive(Debug)]
pub struct PausedEvent {
    pub pool: Pubkey,
    pub paused: bool,
    /// H-06 fix (#62 c.4527806799): which authority key triggered the
    /// state change. Pre-fix this event was unaccountable — auditor
    /// couldn't trace a specific multisig signer back to a pause action.
    pub caller: Pubkey,
    /// On-chain timestamp at the pause toggle. Pairs with caller for
    /// incident-response timeline reconstruction.
    pub ts: i64,
}

#[event]
#[derive(Debug)]
pub struct PoolInitialized {
    pub pool: Pubkey,
    pub authority: Pubkey,
    pub usdc_mint: Pubkey,
    pub ping_mint: Pubkey,
    pub usdc_vault: Pubkey,
    pub ping_vault: Pubkey,
    pub spread_bps: u16,
    pub bump: u8,
}

#[event]
#[derive(Debug)]
pub struct AuthorityRotated {
    pub pool: Pubkey,
    pub old_authority: Pubkey,
    pub new_authority: Pubkey,
}

#[error_code]
pub enum SwapError {
    #[msg("Pool is paused")]
    Paused,
    #[msg("Amount must be > 0")]
    ZeroAmount,
    #[msg("Output too small (below dust)")]
    OutputTooSmall,
    #[msg("Insufficient pool liquidity")]
    InsufficientLiquidity,
    #[msg("Spread BPS exceeds MAX_SPREAD_BPS")]
    SpreadTooHigh,
    #[msg("Arithmetic overflow")]
    MathOverflow,
    #[msg("vault.owner must equal the pool PDA")]
    WrongVaultOwner,
    #[msg("vault.mint must equal the corresponding mint passed to initialize_pool")]
    WrongVaultMint,
    #[msg("vault.close_authority must be None (vault must not be closeable)")]
    VaultMustNotBeCloseable,
    #[msg("Slippage exceeded — actual output below minimum_amount_out (sandwich-attack defense)")]
    SlippageExceeded,
    #[msg("New authority cannot be the zero pubkey")]
    ZeroPubkey,
    #[msg("Claimed authority is not the expected Squads multisig vault PDA (H-02)")]
    WrongAuthority,
    #[msg("AMM price deviates from Pyth oracle beyond MAX_ORACLE_DEVIATION_BPS — sandwich/manipulation defense")]
    PriceDeviatesFromOracle,
    #[msg("Pyth price account could not be parsed as a SolanaPriceAccount")]
    OracleAccountInvalid,
    #[msg("Pyth price is stale (>MAX_PYTH_STALENESS_SEC since last update) or non-positive")]
    OracleStaleOrInvalid,
}
