{{- if .Values.secrets.external.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app.kubernetes.io/name: ping-user
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: user
    app.kubernetes.io/part-of: ping
spec:
  refreshInterval: 60s
  secretStoreRef:
    name: {{ .Values.secrets.external.storeName }}
    kind: ClusterSecretStore
  target:
    name: {{ .Release.Name }}-secrets
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_URL
      remoteRef:
        key: {{ .Values.secrets.external.paths.postgresUrl }}
    - secretKey: JWT_SECRET
      remoteRef:
        key: {{ .Values.secrets.external.paths.jwtSecret }}
{{- end }}
