use anchor_lang::prelude::*;
use anchor_spl::token_interface::{
    self, Mint, TokenAccount, TokenInterface, TransferChecked, MintTo,
};

// ============================================================================
// ⚠️  DO NOT DEPLOY THIS PROGRAM TO MAINNET — per ADR 0018 + #22 EPIC gates.
// ============================================================================
// Pre-audit review 2026-05-24 (#22 c.4527111355) surfaced 22 findings:
//   - 4 Critical: first-depositor inflation; harvest accepts caller-supplied
//     yield_amount with no verification + no adapter CPI (ADR 0017 violation —
//     operator could drain vault); initialize_vault doesn't constrain vUSDC
//     mint_authority to vault PDA; PDA seed [b"vault"] front-runnable
//   - 5 High: no DO-NOT-DEPLOY guard (closed by this comment), single-signer
//     pause, pause-blocks-unstake (locks users out), missing emergency_withdraw
//     + rotate_authority, no solvency invariant
//
// Meta-finding: this scaffold implements ~5% of ADR 0012. The right path is
// a full rebuild per ADR 0012 (adapter CPIs to Kamino/Marginfi/Aave/Drift,
// Jupiter swap-to-$PING, share PDA per user, solvency invariant assert,
// multisig + 7d timelock, emergency_withdraw) — NOT band-aid Critical fixes
// on a fundamentally incomplete program.
//
// Mainnet deploy is gated on (per #22 EPIC):
//   1. Full ADR 0012 implementation (per-Wave Phase-2 issue, not this scaffold)
//   2. OtterSec audit + critical/high findings remediated
//   3. Cayman Foundation incorporation
//   4. Real program keypair generated by Squads multisig
//
// The placeholder declare_id! below cannot be deployed to mainnet (no signer
// for that pubkey exists).
//
// L-01 ADR 0018 compile_error guard (mirrors ping-token 2bd1c24): mainnet-ready
// feature flag requires audit-passed; replacing the placeholder declare_id
// without OtterSec sign-off fails compilation.
#[cfg(all(feature = "mainnet-ready", not(feature = "audit-passed")))]
compile_error!(
    "earn-vault: mainnet-ready feature requires audit-passed feature \
     (set only AFTER OtterSec audit completes per #22 EPIC + ADR 0018)"
);
declare_id!("EarnVau1tProgr4mPubKeyP1aceooo1111111111111");

/// Squads V4 multisig program ID (mainnet) + vault PDA derivation.
/// Mirrors the pattern shipped in internal-swap + pomm (2430d03) so the
/// audit-pass authority migration path is identical across all 4 programs.
///
/// At mainnet deploy time the vault.authority field is rotated to the
/// vault PDA derived from a Squads multisig that the Cayman Foundation
/// holds the N-of-M signing keys for. Until that ceremony lands the
/// `authority` is a single-key devnet keypair — and the production-only
/// invariant `vault.authority == squads_multisig::vault_pda(...)` is
/// enforced ONLY when `feature = "audit-passed"` is set per the L-01
/// guard above (cf. ADR 0018).
pub mod squads_multisig {
    use anchor_lang::prelude::*;

    /// The mainnet Squads V4 program ID. The scaffold derives PDAs locally
    /// for verification purposes — the actual CPI to Squads (proposal
    /// status check on rotate / emergency_withdraw / set_paused) lands when
    /// the squads-protocol-sdk crate is fetchable per runbook 584c169 Step 1.
    pub fn id() -> Pubkey {
        // SQDS4ep65T869zMMBKyuUq6aD6EgTu8psMjkvj52pCf
        Pubkey::try_from("SQDS4ep65T869zMMBKyuUq6aD6EgTu8psMjkvj52pCf")
            .expect("Squads V4 program id is a valid base58 pubkey")
    }

    /// Derive the vault PDA for a Squads multisig at a given vault_index.
    /// vault_index = 0 is the convention for the primary signing vault.
    pub fn vault_pda(multisig_pda: &Pubkey, vault_index: u8) -> (Pubkey, u8) {
        Pubkey::find_program_address(
            &[
                b"multisig",
                multisig_pda.as_ref(),
                b"vault",
                &[vault_index],
            ],
            &id(),
        )
    }

    /// Authority-guard helper: assert the given key matches the Squads vault PDA
    /// derived from the recorded `multisig_pda`. Returns Ok(()) when matches.
    pub fn assert_is_vault_pda(
        candidate: &Pubkey,
        multisig_pda: &Pubkey,
        vault_index: u8,
    ) -> Result<()> {
        let (expected, _bump) = vault_pda(multisig_pda, vault_index);
        require_keys_eq!(*candidate, expected, super::VaultError::WrongAuthority);
        Ok(())
    }
}

/// USDC has 6 decimals on Solana mainnet. 1000 USDC = 1_000_000_000 atomic
/// units. Pre-audit C-01 mitigation: first stake must be ≥ this to prevent
/// share-price inflation attack against the empty vault.
pub const MIN_FIRST_STAKE: u64 = 1_000_000_000;

/// Pre-audit H-04 ADR 0019 governance timelock: authority rotation MUST be
/// a 2-step process with a 7-day delay between proposal + finalisation.
/// The delay window gives independent watchers + the wider community time
/// to react to a malicious multisig signer + revoke the proposal via
/// `cancel_authority_rotation`. 7 days × 86400 seconds = 604_800.
pub const AUTHORITY_ROTATION_TIMELOCK_SEC: i64 = 7 * 86_400;

/// Pre-audit H-05 solvency invariant: the sum of (idle USDC in usdc_vault +
/// total deployed to adapters) MUST be >= total_staked at every state-mutating
/// instruction's end. The current scaffold has no adapter deployment, so the
/// invariant reduces to `usdc_vault.amount >= total_staked`. This catches:
///   - direct vault drains (someone with token authority moves USDC out)
///   - rounding bugs in share math that under-track total_staked
///   - rebuild-introduced bugs where an adapter-CPI lands wrong amount back
///
/// When the rebuild (#61) wires real adapter CPIs, this same helper extends
/// to `usdc_vault.amount + adapter_deployed_total >= total_staked`. For now
/// the no-adapter form catches every direct-drain class issue.
pub fn assert_solvency_unchecked(
    usdc_vault_amount: u64,
    total_staked: u64,
) -> Result<()> {
    require!(
        usdc_vault_amount >= total_staked,
        VaultError::SolvencyInvariantBroken
    );
    Ok(())
}

#[program]
pub mod earn_vault {
    use super::*;

    pub fn initialize_vault(ctx: Context<InitializeVault>, treasury_bps: u16) -> Result<()> {
        require!(treasury_bps <= 10_000, VaultError::InvalidBps);
        let vault = &mut ctx.accounts.vault;
        vault.authority = ctx.accounts.authority.key();
        vault.usdc_mint = ctx.accounts.usdc_mint.key();
        vault.vusdc_mint = ctx.accounts.vusdc_mint.key();
        vault.treasury = ctx.accounts.treasury.key();
        vault.usdc_vault = ctx.accounts.usdc_vault.key();
        vault.treasury_split_bps = treasury_bps;
        vault.holder_split_bps = 10_000 - treasury_bps;
        vault.total_staked = 0;
        vault.total_vusdc_supply = 0;
        vault.is_paused = false;
        vault.bump = ctx.bumps.vault;
        vault.pending_authority = Pubkey::default();
        vault.pending_authority_unlock_ts = 0;

        // M-class cross-applied from internal-swap M-04 (eace98f):
        // indexers subscribe to creation event instead of crawling.
        emit!(VaultInitialized {
            vault: vault.key(),
            authority: vault.authority,
            usdc_mint: vault.usdc_mint,
            vusdc_mint: vault.vusdc_mint,
            usdc_vault: vault.usdc_vault,
            treasury: vault.treasury,
            treasury_split_bps: vault.treasury_split_bps,
            holder_split_bps: vault.holder_split_bps,
            bump: vault.bump,
        });
        Ok(())
    }

    pub fn stake(ctx: Context<Stake>, amount: u64) -> Result<()> {
        require!(!ctx.accounts.vault.is_paused, VaultError::Paused);
        require!(amount > 0, VaultError::ZeroAmount);

        // Pre-audit C-01 (#22 c.4527111355) — first-depositor inflation
        // mitigation. Standard ERC-4626-style band-aid: require the first
        // deposit (when total_vusdc_supply == 0) to be ≥ MIN_FIRST_STAKE so
        // that an attacker can't seed 1 USDC + donate USDC directly to the
        // vault to inflate the share price, then have the next victim's
        // deposit round to 0 vUSDC. 1000 USDC at 6 decimals raises the
        // attack cost prohibitively even before the per-user share PDA
        // rebuild lands (#61). Survives into the rebuild as belt-and-braces.
        if ctx.accounts.vault.total_vusdc_supply == 0 {
            require!(amount >= MIN_FIRST_STAKE, VaultError::FirstStakeTooSmall);
        }

        token_interface::transfer_checked(
            ctx.accounts.transfer_to_vault_ctx(),
            amount,
            ctx.accounts.usdc_mint.decimals,
        )?;

        let vusdc_amount = if ctx.accounts.vault.total_vusdc_supply == 0 {
            amount
        } else {
            (amount as u128)
                .checked_mul(ctx.accounts.vault.total_vusdc_supply as u128)
                .ok_or(VaultError::MathOverflow)?
                .checked_div(ctx.accounts.vault.total_staked as u128)
                .ok_or(VaultError::MathOverflow)? as u64
        };

        let vault_key = ctx.accounts.vault.key();
        // C-04 fix: signer seeds must include usdc_mint to match the per-mint
        // PDA bound at initialize_vault. Read from vault.usdc_mint (recorded
        // at init) — that pubkey IS the binding identity of this vault.
        let usdc_mint_key = ctx.accounts.vault.usdc_mint;
        let seeds = &[
            b"vault".as_ref(),
            usdc_mint_key.as_ref(),
            &[ctx.accounts.vault.bump],
        ];
        let signer = &[&seeds[..]];
        token_interface::mint_to(
            ctx.accounts.mint_vusdc_ctx().with_signer(signer),
            vusdc_amount,
        )?;

        let vault = &mut ctx.accounts.vault;
        vault.total_staked = vault
            .total_staked
            .checked_add(amount)
            .ok_or(VaultError::MathOverflow)?;
        vault.total_vusdc_supply = vault
            .total_vusdc_supply
            .checked_add(vusdc_amount)
            .ok_or(VaultError::MathOverflow)?;

        emit!(StakeEvent {
            user: ctx.accounts.user.key(),
            vault: vault_key,
            usdc_amount: amount,
            vusdc_amount,
        });

        // H-05 solvency invariant — re-fetch usdc_vault amount after the
        // CPI transfer landed; assert idle balance covers total_staked.
        ctx.accounts.usdc_vault.reload()?;
        assert_solvency_unchecked(
            ctx.accounts.usdc_vault.amount,
            ctx.accounts.vault.total_staked,
        )?;
        Ok(())
    }

    /// SCAFFOLD-LIFETIME DEFENSIVE NO-OP. Pre-audit finding C-02
    /// (#22 c.4527111355) — original harvest() accepted caller-supplied
    /// yield_amount with zero verification AND performed no adapter CPI,
    /// so an operator could call harvest(yield_amount = anything) and the
    /// vault would credit the treasury share + inflate total_staked
    /// without any actual yield being earned. Direct ADR 0017 violation
    /// (operator-only authority path to user funds).
    ///
    /// Until the ADR 0012 rebuild lands real adapter CPIs (#61), harvest()
    /// is hard-disabled — every call reverts with HarvestDisabledUntilRebuild.
    /// This makes the C-02 attack PHYSICALLY IMPOSSIBLE for the
    /// scaffold-lifetime regardless of who calls it.
    pub fn harvest(_ctx: Context<Harvest>, _yield_amount: u64) -> Result<()> {
        err!(VaultError::HarvestDisabledUntilRebuild)
    }

    pub fn unstake(ctx: Context<Unstake>, vusdc_amount: u64) -> Result<()> {
        // Pre-audit H-03 (#22 c.4527111355) — unstake MUST NEVER be blocked
        // by pause. Financial-safety invariant: users always retain the right
        // to exit the vault, even (especially) during emergencies. Pause
        // blocks new stakes + harvest, not withdrawals.
        require!(vusdc_amount > 0, VaultError::ZeroAmount);

        let usdc_amount = (vusdc_amount as u128)
            .checked_mul(ctx.accounts.vault.total_staked as u128)
            .ok_or(VaultError::MathOverflow)?
            .checked_div(ctx.accounts.vault.total_vusdc_supply as u128)
            .ok_or(VaultError::MathOverflow)? as u64;

        // C-04 fix: signer seeds must include usdc_mint to match the per-mint
        // PDA bound at initialize_vault. Read from vault.usdc_mint (recorded
        // at init) — that pubkey IS the binding identity of this vault.
        let usdc_mint_key = ctx.accounts.vault.usdc_mint;
        let seeds = &[
            b"vault".as_ref(),
            usdc_mint_key.as_ref(),
            &[ctx.accounts.vault.bump],
        ];
        let signer = &[&seeds[..]];
        token_interface::transfer_checked(
            ctx.accounts.transfer_to_user_ctx().with_signer(signer),
            usdc_amount,
            ctx.accounts.usdc_mint.decimals,
        )?;
        token_interface::burn(
            ctx.accounts.burn_vusdc_ctx(),
            vusdc_amount,
        )?;

        let vault = &mut ctx.accounts.vault;
        vault.total_staked = vault
            .total_staked
            .checked_sub(usdc_amount)
            .ok_or(VaultError::MathOverflow)?;
        vault.total_vusdc_supply = vault
            .total_vusdc_supply
            .checked_sub(vusdc_amount)
            .ok_or(VaultError::MathOverflow)?;

        emit!(UnstakeEvent {
            user: ctx.accounts.user.key(),
            vault: vault.key(),
            vusdc_amount,
            usdc_amount,
        });

        // H-05 solvency invariant — re-fetch usdc_vault amount after the
        // outbound transfer; remaining idle balance must still cover the
        // (now-decremented) total_staked.
        ctx.accounts.usdc_vault.reload()?;
        assert_solvency_unchecked(
            ctx.accounts.usdc_vault.amount,
            ctx.accounts.vault.total_staked,
        )?;
        Ok(())
    }

    pub fn set_paused(ctx: Context<SetPaused>, paused: bool) -> Result<()> {
        ctx.accounts.vault.is_paused = paused;
        emit!(PausedEvent {
            vault: ctx.accounts.vault.key(),
            paused,
        });
        Ok(())
    }

    /// Step 1 of 2-step authority rotation per ADR 0019 + #61 batch-2.
    /// Proposes a new authority and starts a 7-day timelock; finalisation
    /// is a SEPARATE call after AUTHORITY_ROTATION_TIMELOCK_SEC elapses.
    ///
    /// During the window:
    ///   - `cancel_authority_rotation` (callable by CURRENT authority) can
    ///     abort the pending rotation if a multisig signer turns hostile
    ///     between propose + finalize
    ///   - on-chain watchers see the pending-authority field and can alarm
    ///   - the existing authority retains full control (no half-rotated
    ///     state where two parties think they're in charge)
    pub fn propose_authority_rotation(
        ctx: Context<ProposeAuthorityRotation>,
        new_authority: Pubkey,
    ) -> Result<()> {
        require!(new_authority != Pubkey::default(), VaultError::ZeroPubkey);
        require!(
            new_authority != ctx.accounts.vault.authority,
            VaultError::SameAuthority
        );
        let now = Clock::get()?.unix_timestamp;
        let unlock_ts = now
            .checked_add(AUTHORITY_ROTATION_TIMELOCK_SEC)
            .ok_or(VaultError::MathOverflow)?;
        ctx.accounts.vault.pending_authority = new_authority;
        ctx.accounts.vault.pending_authority_unlock_ts = unlock_ts;
        emit!(AuthorityRotationProposed {
            vault: ctx.accounts.vault.key(),
            current_authority: ctx.accounts.vault.authority,
            proposed_authority: new_authority,
            unlock_ts,
            ts: now,
        });
        Ok(())
    }

    /// Step 2 of 2 — finalise the rotation after the 7-day timelock elapses.
    /// Callable by ANYONE (intentional: the new authority should be able to
    /// pull-pattern claim ownership; the current authority could otherwise
    /// stall the rotation indefinitely by refusing to call finalize).
    pub fn finalize_authority_rotation(
        ctx: Context<FinalizeAuthorityRotation>,
    ) -> Result<()> {
        let now = Clock::get()?.unix_timestamp;
        require!(
            ctx.accounts.vault.pending_authority != Pubkey::default(),
            VaultError::NoPendingRotation
        );
        require!(
            now >= ctx.accounts.vault.pending_authority_unlock_ts,
            VaultError::TimelockNotElapsed
        );
        let old_authority = ctx.accounts.vault.authority;
        let new_authority = ctx.accounts.vault.pending_authority;
        ctx.accounts.vault.authority = new_authority;
        ctx.accounts.vault.pending_authority = Pubkey::default();
        ctx.accounts.vault.pending_authority_unlock_ts = 0;
        emit!(AuthorityRotated {
            vault: ctx.accounts.vault.key(),
            old_authority,
            new_authority,
        });
        Ok(())
    }

    /// Cancel a pending rotation. Callable ONLY by the CURRENT authority
    /// (so a hostile pending-authority can't pre-empt cancel). Use case:
    /// proposing the wrong key, OR detecting a malicious signer between
    /// the propose + finalize calls.
    pub fn cancel_authority_rotation(
        ctx: Context<CancelAuthorityRotation>,
    ) -> Result<()> {
        require!(
            ctx.accounts.vault.pending_authority != Pubkey::default(),
            VaultError::NoPendingRotation
        );
        let cancelled = ctx.accounts.vault.pending_authority;
        ctx.accounts.vault.pending_authority = Pubkey::default();
        ctx.accounts.vault.pending_authority_unlock_ts = 0;
        emit!(AuthorityRotationCancelled {
            vault: ctx.accounts.vault.key(),
            cancelled_authority: cancelled,
            ts: Clock::get()?.unix_timestamp,
        });
        Ok(())
    }

    /// Emergency withdraw — Pre-audit H-04 full (#22 c.4527111355). Allows
    /// the vault authority (production: Squads multisig) to sweep idle USDC
    /// from the vault's reserve to a multisig-controlled destination. Use
    /// case: oracle exploit / adapter compromise where we need to halt user
    /// activity AND extract reserves before an exploit drains them.
    ///
    /// Defense-in-depth: requires `vault.is_paused == true` first so the
    /// founder can't quietly drain a live vault. Pause MUST be the explicit
    /// step that precedes any emergency_withdraw call — set_paused emits
    /// PausedEvent which on-chain monitors alarm on.
    ///
    /// Destination is constrained by the EmergencyWithdraw context to be
    /// owned by the vault authority (the multisig PDA in production), so
    /// funds can't be misdirected to an attacker-controlled account by a
    /// single rogue signer.
    pub fn emergency_withdraw(
        ctx: Context<EmergencyWithdraw>,
        amount: u64,
    ) -> Result<()> {
        require!(ctx.accounts.vault.is_paused, VaultError::MustPauseFirst);
        require!(amount > 0, VaultError::ZeroAmount);

        let usdc_mint_key = ctx.accounts.vault.usdc_mint;
        let seeds = &[
            b"vault".as_ref(),
            usdc_mint_key.as_ref(),
            &[ctx.accounts.vault.bump],
        ];
        let signer = &[&seeds[..]];
        token_interface::transfer_checked(
            ctx.accounts.transfer_to_destination_ctx().with_signer(signer),
            amount,
            ctx.accounts.usdc_mint.decimals,
        )?;

        emit!(EmergencyWithdrawEvent {
            vault: ctx.accounts.vault.key(),
            authority: ctx.accounts.authority.key(),
            destination: ctx.accounts.destination.key(),
            amount,
            ts: Clock::get()?.unix_timestamp,
        });

        // Solvency invariant is INTENTIONALLY NOT asserted here. The whole
        // point of emergency_withdraw is to break vault.total_staked >=
        // usdc_vault.amount when the vault has been compromised. The audit
        // expectation: once emergency_withdraw fires, the operator pursues
        // the post-incident playbook (close the vault, refund users from
        // the recovered USDC + treasury per ADR 0019 §incidents).
        Ok(())
    }
}

#[derive(Accounts)]
pub struct ProposeAuthorityRotation<'info> {
    #[account(
        mut,
        seeds = [b"vault", usdc_mint.key().as_ref()],
        bump = vault.bump,
        has_one = authority @ VaultError::WrongAuthority,
    )]
    pub vault: Account<'info, Vault>,
    /// Current authority — must sign.
    pub authority: Signer<'info>,
    pub usdc_mint: InterfaceAccount<'info, Mint>,
}

#[derive(Accounts)]
pub struct FinalizeAuthorityRotation<'info> {
    /// Per-mint Vault PDA. NB: no has_one constraint — anyone can call
    /// finalize after the timelock; pending-authority pubkey-binding is
    /// asserted inside the instruction body.
    #[account(
        mut,
        seeds = [b"vault", usdc_mint.key().as_ref()],
        bump = vault.bump,
    )]
    pub vault: Account<'info, Vault>,
    pub usdc_mint: InterfaceAccount<'info, Mint>,
    /// Any signer can call finalize — the new authority pulls ownership
    /// via the on-chain pending_authority field.
    pub caller: Signer<'info>,
}

#[derive(Accounts)]
pub struct CancelAuthorityRotation<'info> {
    #[account(
        mut,
        seeds = [b"vault", usdc_mint.key().as_ref()],
        bump = vault.bump,
        has_one = authority @ VaultError::WrongAuthority,
    )]
    pub vault: Account<'info, Vault>,
    /// Current authority must sign to cancel.
    pub authority: Signer<'info>,
    pub usdc_mint: InterfaceAccount<'info, Mint>,
}

#[account]
#[derive(Debug)]
pub struct Vault {
    pub authority: Pubkey,
    pub usdc_mint: Pubkey,
    pub vusdc_mint: Pubkey,
    pub treasury: Pubkey,
    pub usdc_vault: Pubkey,
    pub total_staked: u64,
    pub total_vusdc_supply: u64,
    pub treasury_split_bps: u16,
    pub holder_split_bps: u16,
    pub is_paused: bool,
    pub bump: u8,
    // #61 batch-2 — ADR 0019 7-day timelock on authority rotation. When a
    // rotation is in flight, pending_authority is non-default + unlock_ts
    // marks the earliest time finalize_authority_rotation may succeed.
    // Zero-sentinel pattern (Pubkey::default() / 0 = no pending rotation)
    // keeps the struct flat + skips Option<> discriminator overhead.
    pub pending_authority: Pubkey,
    pub pending_authority_unlock_ts: i64,
}

impl Vault {
    // 8 (discriminator) + 32×5 (pubkeys) + 8×2 (u64s) + 2×2 (u16s) + 1 + 1
    // + 32 (pending_authority) + 8 (pending_authority_unlock_ts)
    pub const LEN: usize = 8 + 32 * 5 + 8 * 2 + 2 * 2 + 1 + 1 + 32 + 8;
}

#[derive(Accounts)]
pub struct InitializeVault<'info> {
    #[account(mut)]
    pub authority: Signer<'info>,
    #[account(
        init,
        payer = authority,
        space = Vault::LEN,
        seeds = [b"vault", usdc_mint.key().as_ref()],
        bump
    )]
    pub vault: Account<'info, Vault>,
    pub usdc_mint: InterfaceAccount<'info, Mint>,
    // Pre-audit C-03 (#22 c.4527111355): without these constraints the
    // deployer could pass a vusdc_mint whose mint_authority points at
    // themselves (back-door: mint unlimited vUSDC for themselves later,
    // burn to drain the vault). Same risk on usdc_vault ownership: if
    // owner isn't the vault PDA, vault can't actually transfer those
    // tokens, OR worse, someone else can.
    #[account(
        constraint = vusdc_mint.mint_authority.is_some()
            && vusdc_mint.mint_authority.unwrap() == vault.key()
            @ VaultError::WrongVusdcMintAuthority,
        constraint = vusdc_mint.freeze_authority.is_none()
            @ VaultError::VusdcFreezeAuthorityMustBeNone,
        constraint = vusdc_mint.supply == 0
            @ VaultError::VusdcMustBeEmptyAtInit,
    )]
    pub vusdc_mint: InterfaceAccount<'info, Mint>,
    #[account(
        constraint = usdc_vault.owner == vault.key()
            @ VaultError::WrongUsdcVaultOwner,
        constraint = usdc_vault.mint == usdc_mint.key()
            @ VaultError::WrongUsdcVaultMint,
    )]
    pub usdc_vault: InterfaceAccount<'info, TokenAccount>,
    pub treasury: InterfaceAccount<'info, TokenAccount>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct Stake<'info> {
    /// Depositor — pays the USDC + receives the vUSDC. Signs the transfer.
    #[account(mut)]
    pub user: Signer<'info>,
    /// Per-mint Vault PDA (C-04 f7ea54f). mut because total_staked +
    /// total_vusdc_supply increment in this instruction.
    #[account(mut, seeds = [b"vault", usdc_mint.key().as_ref()], bump = vault.bump)]
    pub vault: Account<'info, Vault>,
    /// USDC mint (mainnet pubkey EPjFWdd5...). Read-only — used for the
    /// transfer_checked decimals enforcement.
    pub usdc_mint: InterfaceAccount<'info, Mint>,
    /// vUSDC mint, authority = vault PDA (enforced at init per C-03 2c35aee).
    /// mut because mint_to CPI increments supply.
    #[account(mut)]
    pub vusdc_mint: InterfaceAccount<'info, Mint>,
    /// Sender of the USDC. Owned by `user` (signer).
    #[account(mut)]
    pub user_usdc_ata: InterfaceAccount<'info, TokenAccount>,
    /// Vault's USDC reserve (owner == vault PDA per C-03 2c35aee).
    /// address = vault.usdc_vault pins to the registered account.
    #[account(mut, address = vault.usdc_vault)]
    pub usdc_vault: InterfaceAccount<'info, TokenAccount>,
    /// Recipient of the vUSDC mint_to.
    #[account(mut)]
    pub user_vusdc_ata: InterfaceAccount<'info, TokenAccount>,
    pub token_program: Interface<'info, TokenInterface>,
}

impl<'info> Stake<'info> {
    fn transfer_to_vault_ctx(&self) -> CpiContext<'_, '_, '_, 'info, TransferChecked<'info>> {
        CpiContext::new(
            self.token_program.to_account_info(),
            TransferChecked {
                from: self.user_usdc_ata.to_account_info(),
                mint: self.usdc_mint.to_account_info(),
                to: self.usdc_vault.to_account_info(),
                authority: self.user.to_account_info(),
            },
        )
    }
    fn mint_vusdc_ctx(&self) -> CpiContext<'_, '_, '_, 'info, MintTo<'info>> {
        CpiContext::new(
            self.token_program.to_account_info(),
            MintTo {
                mint: self.vusdc_mint.to_account_info(),
                to: self.user_vusdc_ata.to_account_info(),
                authority: self.vault.to_account_info(),
            },
        )
    }
}

#[derive(Accounts)]
pub struct Harvest<'info> {
    /// Vault authority — must match recorded vault.authority (production:
    /// Squads multisig). NB: harvest() instruction itself is hard-disabled
    /// per C-02 61407a3 — this context is preserved for the #61 rebuild.
    #[account(mut, address = vault.authority)]
    pub authority: Signer<'info>,
    /// Per-mint Vault PDA. Even though harvest() reverts, the seeds /
    /// constraints must remain valid so the call reaches the err! shorthand.
    #[account(mut, seeds = [b"vault", usdc_mint.key().as_ref()], bump = vault.bump)]
    pub vault: Account<'info, Vault>,
    /// USDC mint — read-only.
    pub usdc_mint: InterfaceAccount<'info, Mint>,
    /// Vault's USDC reserve (would source the yield-distribution transfer
    /// post-rebuild; currently unused since harvest reverts).
    #[account(mut, address = vault.usdc_vault)]
    pub usdc_vault: InterfaceAccount<'info, TokenAccount>,
    /// Treasury (would receive treasury_split_bps × yield post-rebuild).
    #[account(mut, address = vault.treasury)]
    pub treasury: InterfaceAccount<'info, TokenAccount>,
    pub token_program: Interface<'info, TokenInterface>,
}

impl<'info> Harvest<'info> {
    fn transfer_to_treasury_ctx(&self) -> CpiContext<'_, '_, '_, 'info, TransferChecked<'info>> {
        CpiContext::new(
            self.token_program.to_account_info(),
            TransferChecked {
                from: self.usdc_vault.to_account_info(),
                mint: self.usdc_mint.to_account_info(),
                to: self.treasury.to_account_info(),
                authority: self.vault.to_account_info(),
            },
        )
    }
}

#[derive(Accounts)]
pub struct Unstake<'info> {
    /// Withdrawer — burns vUSDC + receives USDC. Pause doesn't block this
    /// per H-03 (2ebfba9) — financial-safety invariant.
    #[account(mut)]
    pub user: Signer<'info>,
    /// Per-mint Vault PDA; mut for total_staked/total_vusdc_supply decrement.
    #[account(mut, seeds = [b"vault", usdc_mint.key().as_ref()], bump = vault.bump)]
    pub vault: Account<'info, Vault>,
    pub usdc_mint: InterfaceAccount<'info, Mint>,
    /// vUSDC mint; mut because burn decrements supply.
    #[account(mut)]
    pub vusdc_mint: InterfaceAccount<'info, Mint>,
    /// Vault's USDC reserve (source of withdrawal).
    #[account(mut, address = vault.usdc_vault)]
    pub usdc_vault: InterfaceAccount<'info, TokenAccount>,
    /// Recipient of the USDC payout.
    #[account(mut)]
    pub user_usdc_ata: InterfaceAccount<'info, TokenAccount>,
    /// User's vUSDC source (burned in this instruction).
    #[account(mut)]
    pub user_vusdc_ata: InterfaceAccount<'info, TokenAccount>,
    pub token_program: Interface<'info, TokenInterface>,
}

impl<'info> Unstake<'info> {
    fn transfer_to_user_ctx(&self) -> CpiContext<'_, '_, '_, 'info, TransferChecked<'info>> {
        CpiContext::new(
            self.token_program.to_account_info(),
            TransferChecked {
                from: self.usdc_vault.to_account_info(),
                mint: self.usdc_mint.to_account_info(),
                to: self.user_usdc_ata.to_account_info(),
                authority: self.vault.to_account_info(),
            },
        )
    }
    fn burn_vusdc_ctx(&self) -> CpiContext<'_, '_, '_, 'info, anchor_spl::token_interface::Burn<'info>> {
        CpiContext::new(
            self.token_program.to_account_info(),
            anchor_spl::token_interface::Burn {
                mint: self.vusdc_mint.to_account_info(),
                from: self.user_vusdc_ata.to_account_info(),
                authority: self.user.to_account_info(),
            },
        )
    }
}

#[derive(Accounts)]
pub struct SetPaused<'info> {
    #[account(address = vault.authority)]
    pub authority: Signer<'info>,
    #[account(mut, seeds = [b"vault", usdc_mint.key().as_ref()], bump = vault.bump)]
    pub vault: Account<'info, Vault>,
    /// usdc_mint included so the per-mint vault PDA seed binding holds.
    pub usdc_mint: InterfaceAccount<'info, Mint>,
}

#[derive(Accounts)]
pub struct EmergencyWithdraw<'info> {
    /// Vault authority (production: Squads multisig vault PDA). Pause MUST
    /// be true before this can succeed — see emergency_withdraw body.
    #[account(address = vault.authority)]
    pub authority: Signer<'info>,
    /// Per-mint Vault PDA — signs the outbound transfer via signer seeds.
    /// Not mut: emergency_withdraw doesn't decrement total_staked because
    /// the post-incident playbook reconstitutes the user-share accounting
    /// off-chain from on-chain events (per ADR 0019 §incidents).
    #[account(seeds = [b"vault", usdc_mint.key().as_ref()], bump = vault.bump)]
    pub vault: Account<'info, Vault>,
    pub usdc_mint: InterfaceAccount<'info, Mint>,
    /// Vault's USDC reserve (source).
    #[account(mut, address = vault.usdc_vault)]
    pub usdc_vault: InterfaceAccount<'info, TokenAccount>,
    /// Recipient — MUST be owned by the vault authority (multisig PDA in
    /// production). Belt-and-braces against a rogue signer redirecting funds.
    #[account(
        mut,
        constraint = destination.owner == authority.key()
            @ VaultError::EmergencyDestinationNotMultisigOwned,
        constraint = destination.mint == usdc_mint.key()
            @ VaultError::WrongUsdcVaultMint,
    )]
    pub destination: InterfaceAccount<'info, TokenAccount>,
    pub token_program: Interface<'info, TokenInterface>,
}

impl<'info> EmergencyWithdraw<'info> {
    fn transfer_to_destination_ctx(
        &self,
    ) -> CpiContext<'_, '_, '_, 'info, TransferChecked<'info>> {
        CpiContext::new(
            self.token_program.to_account_info(),
            TransferChecked {
                from: self.usdc_vault.to_account_info(),
                mint: self.usdc_mint.to_account_info(),
                to: self.destination.to_account_info(),
                authority: self.vault.to_account_info(),
            },
        )
    }
}

#[event]
#[derive(Debug)]
pub struct StakeEvent {
    pub user: Pubkey,
    pub vault: Pubkey,
    pub usdc_amount: u64,
    pub vusdc_amount: u64,
}

#[event]
#[derive(Debug)]
pub struct UnstakeEvent {
    pub user: Pubkey,
    pub vault: Pubkey,
    pub vusdc_amount: u64,
    pub usdc_amount: u64,
}

#[event]
#[derive(Debug)]
pub struct HarvestEvent {
    pub vault: Pubkey,
    pub yield_amount: u64,
    pub treasury_share: u64,
    pub holder_share: u64,
}

#[event]
#[derive(Debug)]
pub struct PausedEvent {
    pub vault: Pubkey,
    pub paused: bool,
}

#[event]
#[derive(Debug)]
pub struct AuthorityRotated {
    pub vault: Pubkey,
    pub old_authority: Pubkey,
    pub new_authority: Pubkey,
}

#[event]
#[derive(Debug)]
pub struct AuthorityRotationProposed {
    pub vault: Pubkey,
    pub current_authority: Pubkey,
    pub proposed_authority: Pubkey,
    pub unlock_ts: i64,
    pub ts: i64,
}

#[event]
#[derive(Debug)]
pub struct AuthorityRotationCancelled {
    pub vault: Pubkey,
    pub cancelled_authority: Pubkey,
    pub ts: i64,
}

#[event]
#[derive(Debug)]
pub struct EmergencyWithdrawEvent {
    pub vault: Pubkey,
    pub authority: Pubkey,
    pub destination: Pubkey,
    pub amount: u64,
    pub ts: i64,
}

#[event]
#[derive(Debug)]
pub struct VaultInitialized {
    pub vault: Pubkey,
    pub authority: Pubkey,
    pub usdc_mint: Pubkey,
    pub vusdc_mint: Pubkey,
    pub usdc_vault: Pubkey,
    pub treasury: Pubkey,
    pub treasury_split_bps: u16,
    pub holder_split_bps: u16,
    pub bump: u8,
}

#[error_code]
pub enum VaultError {
    #[msg("Vault is paused")]
    Paused,
    #[msg("Amount must be > 0")]
    ZeroAmount,
    #[msg("treasury_bps must be <= 10000")]
    InvalidBps,
    #[msg("Arithmetic overflow")]
    MathOverflow,
    #[msg("harvest() disabled in scaffold; full rebuild per ADR 0012 (#61) required first")]
    HarvestDisabledUntilRebuild,
    #[msg("First stake must be >= 1000 USDC to prevent share-price inflation attack")]
    FirstStakeTooSmall,
    #[msg("vusdc_mint.mint_authority must equal the vault PDA")]
    WrongVusdcMintAuthority,
    #[msg("vusdc_mint.freeze_authority must be None")]
    VusdcFreezeAuthorityMustBeNone,
    #[msg("vusdc_mint must have zero supply at initialize_vault (clean mint)")]
    VusdcMustBeEmptyAtInit,
    #[msg("usdc_vault.owner must equal the vault PDA")]
    WrongUsdcVaultOwner,
    #[msg("usdc_vault.mint must equal the usdc_mint passed to initialize_vault")]
    WrongUsdcVaultMint,
    #[msg("Caller is not the vault authority")]
    WrongAuthority,
    #[msg("New authority cannot be the zero pubkey")]
    ZeroPubkey,
    #[msg("Vault must be paused before emergency_withdraw — set_paused(true) first")]
    MustPauseFirst,
    #[msg("emergency_withdraw destination must be owned by the vault authority (multisig in prod)")]
    EmergencyDestinationNotMultisigOwned,
    #[msg("Solvency invariant broken: usdc_vault.amount < vault.total_staked")]
    SolvencyInvariantBroken,
    #[msg("Proposed authority must differ from current authority")]
    SameAuthority,
    #[msg("No pending authority rotation to finalize/cancel")]
    NoPendingRotation,
    #[msg("Authority rotation timelock (7 days) has not elapsed yet")]
    TimelockNotElapsed,
}
